// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: symplus.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SymplusService_GetFunds_FullMethodName         = "/symplus.SymplusService/GetFunds"
	SymplusService_GetFundAccounts_FullMethodName  = "/symplus.SymplusService/GetFundAccounts"
	SymplusService_FundSubscription_FullMethodName = "/symplus.SymplusService/FundSubscription"
	SymplusService_FundRedemption_FullMethodName   = "/symplus.SymplusService/FundRedemption"
	SymplusService_GetFundPrice_FullMethodName     = "/symplus.SymplusService/GetFundPrice"
)

// SymplusServiceClient is the client API for SymplusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SymplusServiceClient interface {
	GetFunds(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SymplusResponse, error)
	GetFundAccounts(ctx context.Context, in *GetAccountsRequest, opts ...grpc.CallOption) (*SymplusResponse, error)
	FundSubscription(ctx context.Context, in *FundSubscriptionRequest, opts ...grpc.CallOption) (*SymplusResponse, error)
	FundRedemption(ctx context.Context, in *FundRedemptionRequest, opts ...grpc.CallOption) (*SymplusResponse, error)
	GetFundPrice(ctx context.Context, in *FundPriceRequest, opts ...grpc.CallOption) (*SymplusResponse, error)
}

type symplusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSymplusServiceClient(cc grpc.ClientConnInterface) SymplusServiceClient {
	return &symplusServiceClient{cc}
}

func (c *symplusServiceClient) GetFunds(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SymplusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SymplusResponse)
	err := c.cc.Invoke(ctx, SymplusService_GetFunds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *symplusServiceClient) GetFundAccounts(ctx context.Context, in *GetAccountsRequest, opts ...grpc.CallOption) (*SymplusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SymplusResponse)
	err := c.cc.Invoke(ctx, SymplusService_GetFundAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *symplusServiceClient) FundSubscription(ctx context.Context, in *FundSubscriptionRequest, opts ...grpc.CallOption) (*SymplusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SymplusResponse)
	err := c.cc.Invoke(ctx, SymplusService_FundSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *symplusServiceClient) FundRedemption(ctx context.Context, in *FundRedemptionRequest, opts ...grpc.CallOption) (*SymplusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SymplusResponse)
	err := c.cc.Invoke(ctx, SymplusService_FundRedemption_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *symplusServiceClient) GetFundPrice(ctx context.Context, in *FundPriceRequest, opts ...grpc.CallOption) (*SymplusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SymplusResponse)
	err := c.cc.Invoke(ctx, SymplusService_GetFundPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SymplusServiceServer is the server API for SymplusService service.
// All implementations must embed UnimplementedSymplusServiceServer
// for forward compatibility.
type SymplusServiceServer interface {
	GetFunds(context.Context, *Empty) (*SymplusResponse, error)
	GetFundAccounts(context.Context, *GetAccountsRequest) (*SymplusResponse, error)
	FundSubscription(context.Context, *FundSubscriptionRequest) (*SymplusResponse, error)
	FundRedemption(context.Context, *FundRedemptionRequest) (*SymplusResponse, error)
	GetFundPrice(context.Context, *FundPriceRequest) (*SymplusResponse, error)
	mustEmbedUnimplementedSymplusServiceServer()
}

// UnimplementedSymplusServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSymplusServiceServer struct{}

func (UnimplementedSymplusServiceServer) GetFunds(context.Context, *Empty) (*SymplusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFunds not implemented")
}
func (UnimplementedSymplusServiceServer) GetFundAccounts(context.Context, *GetAccountsRequest) (*SymplusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFundAccounts not implemented")
}
func (UnimplementedSymplusServiceServer) FundSubscription(context.Context, *FundSubscriptionRequest) (*SymplusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FundSubscription not implemented")
}
func (UnimplementedSymplusServiceServer) FundRedemption(context.Context, *FundRedemptionRequest) (*SymplusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FundRedemption not implemented")
}
func (UnimplementedSymplusServiceServer) GetFundPrice(context.Context, *FundPriceRequest) (*SymplusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFundPrice not implemented")
}
func (UnimplementedSymplusServiceServer) mustEmbedUnimplementedSymplusServiceServer() {}
func (UnimplementedSymplusServiceServer) testEmbeddedByValue()                        {}

// UnsafeSymplusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SymplusServiceServer will
// result in compilation errors.
type UnsafeSymplusServiceServer interface {
	mustEmbedUnimplementedSymplusServiceServer()
}

func RegisterSymplusServiceServer(s grpc.ServiceRegistrar, srv SymplusServiceServer) {
	// If the following call panics, it indicates UnimplementedSymplusServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SymplusService_ServiceDesc, srv)
}

func _SymplusService_GetFunds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SymplusServiceServer).GetFunds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SymplusService_GetFunds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SymplusServiceServer).GetFunds(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SymplusService_GetFundAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SymplusServiceServer).GetFundAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SymplusService_GetFundAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SymplusServiceServer).GetFundAccounts(ctx, req.(*GetAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SymplusService_FundSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FundSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SymplusServiceServer).FundSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SymplusService_FundSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SymplusServiceServer).FundSubscription(ctx, req.(*FundSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SymplusService_FundRedemption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FundRedemptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SymplusServiceServer).FundRedemption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SymplusService_FundRedemption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SymplusServiceServer).FundRedemption(ctx, req.(*FundRedemptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SymplusService_GetFundPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FundPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SymplusServiceServer).GetFundPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SymplusService_GetFundPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SymplusServiceServer).GetFundPrice(ctx, req.(*FundPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SymplusService_ServiceDesc is the grpc.ServiceDesc for SymplusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SymplusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "symplus.SymplusService",
	HandlerType: (*SymplusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFunds",
			Handler:    _SymplusService_GetFunds_Handler,
		},
		{
			MethodName: "GetFundAccounts",
			Handler:    _SymplusService_GetFundAccounts_Handler,
		},
		{
			MethodName: "FundSubscription",
			Handler:    _SymplusService_FundSubscription_Handler,
		},
		{
			MethodName: "FundRedemption",
			Handler:    _SymplusService_FundRedemption_Handler,
		},
		{
			MethodName: "GetFundPrice",
			Handler:    _SymplusService_GetFundPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "symplus.proto",
}
