// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: symplus.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_symplus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_symplus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_symplus_proto_rawDescGZIP(), []int{0}
}

type GetAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountsRequest) Reset() {
	*x = GetAccountsRequest{}
	mi := &file_symplus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountsRequest) ProtoMessage() {}

func (x *GetAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_symplus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountsRequest.ProtoReflect.Descriptor instead.
func (*GetAccountsRequest) Descriptor() ([]byte, []int) {
	return file_symplus_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccountsRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type FundSubscriptionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CustomerId       string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	FundId           string                 `protobuf:"bytes,2,opt,name=fund_id,json=fundId,proto3" json:"fund_id,omitempty"`
	Amount           float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentReference string                 `protobuf:"bytes,4,opt,name=payment_reference,json=paymentReference,proto3" json:"payment_reference,omitempty"`
	Narration        string                 `protobuf:"bytes,5,opt,name=narration,proto3" json:"narration,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FundSubscriptionRequest) Reset() {
	*x = FundSubscriptionRequest{}
	mi := &file_symplus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FundSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundSubscriptionRequest) ProtoMessage() {}

func (x *FundSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_symplus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*FundSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_symplus_proto_rawDescGZIP(), []int{2}
}

func (x *FundSubscriptionRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *FundSubscriptionRequest) GetFundId() string {
	if x != nil {
		return x.FundId
	}
	return ""
}

func (x *FundSubscriptionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *FundSubscriptionRequest) GetPaymentReference() string {
	if x != nil {
		return x.PaymentReference
	}
	return ""
}

func (x *FundSubscriptionRequest) GetNarration() string {
	if x != nil {
		return x.Narration
	}
	return ""
}

type FundRedemptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	FundId        string                 `protobuf:"bytes,2,opt,name=fund_id,json=fundId,proto3" json:"fund_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Narration     string                 `protobuf:"bytes,4,opt,name=narration,proto3" json:"narration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FundRedemptionRequest) Reset() {
	*x = FundRedemptionRequest{}
	mi := &file_symplus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FundRedemptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundRedemptionRequest) ProtoMessage() {}

func (x *FundRedemptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_symplus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundRedemptionRequest.ProtoReflect.Descriptor instead.
func (*FundRedemptionRequest) Descriptor() ([]byte, []int) {
	return file_symplus_proto_rawDescGZIP(), []int{3}
}

func (x *FundRedemptionRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *FundRedemptionRequest) GetFundId() string {
	if x != nil {
		return x.FundId
	}
	return ""
}

func (x *FundRedemptionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *FundRedemptionRequest) GetNarration() string {
	if x != nil {
		return x.Narration
	}
	return ""
}

type FundPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FundId        string                 `protobuf:"bytes,1,opt,name=fund_id,json=fundId,proto3" json:"fund_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FundPriceRequest) Reset() {
	*x = FundPriceRequest{}
	mi := &file_symplus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FundPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundPriceRequest) ProtoMessage() {}

func (x *FundPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_symplus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundPriceRequest.ProtoReflect.Descriptor instead.
func (*FundPriceRequest) Descriptor() ([]byte, []int) {
	return file_symplus_proto_rawDescGZIP(), []int{4}
}

func (x *FundPriceRequest) GetFundId() string {
	if x != nil {
		return x.FundId
	}
	return ""
}

type SymplusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // JSON encoded response from Symplus
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymplusResponse) Reset() {
	*x = SymplusResponse{}
	mi := &file_symplus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymplusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymplusResponse) ProtoMessage() {}

func (x *SymplusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_symplus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymplusResponse.ProtoReflect.Descriptor instead.
func (*SymplusResponse) Descriptor() ([]byte, []int) {
	return file_symplus_proto_rawDescGZIP(), []int{5}
}

func (x *SymplusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SymplusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SymplusResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_symplus_proto protoreflect.FileDescriptor

const file_symplus_proto_rawDesc = "" +
	"\n" +
	"\rsymplus.proto\x12\asymplus\"\a\n" +
	"\x05Empty\"5\n" +
	"\x12GetAccountsRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\"\xb6\x01\n" +
	"\x17FundSubscriptionRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x17\n" +
	"\afund_id\x18\x02 \x01(\tR\x06fundId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12+\n" +
	"\x11payment_reference\x18\x04 \x01(\tR\x10paymentReference\x12\x1c\n" +
	"\tnarration\x18\x05 \x01(\tR\tnarration\"\x87\x01\n" +
	"\x15FundRedemptionRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x17\n" +
	"\afund_id\x18\x02 \x01(\tR\x06fundId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1c\n" +
	"\tnarration\x18\x04 \x01(\tR\tnarration\"+\n" +
	"\x10FundPriceRequest\x12\x17\n" +
	"\afund_id\x18\x01 \x01(\tR\x06fundId\"Y\n" +
	"\x0fSymplusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data2\xf1\x02\n" +
	"\x0eSymplusService\x124\n" +
	"\bGetFunds\x12\x0e.symplus.Empty\x1a\x18.symplus.SymplusResponse\x12H\n" +
	"\x0fGetFundAccounts\x12\x1b.symplus.GetAccountsRequest\x1a\x18.symplus.SymplusResponse\x12N\n" +
	"\x10FundSubscription\x12 .symplus.FundSubscriptionRequest\x1a\x18.symplus.SymplusResponse\x12J\n" +
	"\x0eFundRedemption\x12\x1e.symplus.FundRedemptionRequest\x1a\x18.symplus.SymplusResponse\x12C\n" +
	"\fGetFundPrice\x12\x19.symplus.FundPriceRequest\x1a\x18.symplus.SymplusResponseB(Z&github.com/gdl/symplus-connector/protob\x06proto3"

var (
	file_symplus_proto_rawDescOnce sync.Once
	file_symplus_proto_rawDescData []byte
)

func file_symplus_proto_rawDescGZIP() []byte {
	file_symplus_proto_rawDescOnce.Do(func() {
		file_symplus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_symplus_proto_rawDesc), len(file_symplus_proto_rawDesc)))
	})
	return file_symplus_proto_rawDescData
}

var file_symplus_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_symplus_proto_goTypes = []any{
	(*Empty)(nil),                   // 0: symplus.Empty
	(*GetAccountsRequest)(nil),      // 1: symplus.GetAccountsRequest
	(*FundSubscriptionRequest)(nil), // 2: symplus.FundSubscriptionRequest
	(*FundRedemptionRequest)(nil),   // 3: symplus.FundRedemptionRequest
	(*FundPriceRequest)(nil),        // 4: symplus.FundPriceRequest
	(*SymplusResponse)(nil),         // 5: symplus.SymplusResponse
}
var file_symplus_proto_depIdxs = []int32{
	0, // 0: symplus.SymplusService.GetFunds:input_type -> symplus.Empty
	1, // 1: symplus.SymplusService.GetFundAccounts:input_type -> symplus.GetAccountsRequest
	2, // 2: symplus.SymplusService.FundSubscription:input_type -> symplus.FundSubscriptionRequest
	3, // 3: symplus.SymplusService.FundRedemption:input_type -> symplus.FundRedemptionRequest
	4, // 4: symplus.SymplusService.GetFundPrice:input_type -> symplus.FundPriceRequest
	5, // 5: symplus.SymplusService.GetFunds:output_type -> symplus.SymplusResponse
	5, // 6: symplus.SymplusService.GetFundAccounts:output_type -> symplus.SymplusResponse
	5, // 7: symplus.SymplusService.FundSubscription:output_type -> symplus.SymplusResponse
	5, // 8: symplus.SymplusService.FundRedemption:output_type -> symplus.SymplusResponse
	5, // 9: symplus.SymplusService.GetFundPrice:output_type -> symplus.SymplusResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_symplus_proto_init() }
func file_symplus_proto_init() {
	if File_symplus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_symplus_proto_rawDesc), len(file_symplus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_symplus_proto_goTypes,
		DependencyIndexes: file_symplus_proto_depIdxs,
		MessageInfos:      file_symplus_proto_msgTypes,
	}.Build()
	File_symplus_proto = out.File
	file_symplus_proto_goTypes = nil
	file_symplus_proto_depIdxs = nil
}
