// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/compliance.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyBVNRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bvn           string                 `protobuf:"bytes,1,opt,name=bvn,proto3" json:"bvn,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyBVNRequest) Reset() {
	*x = VerifyBVNRequest{}
	mi := &file_proto_compliance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyBVNRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyBVNRequest) ProtoMessage() {}

func (x *VerifyBVNRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyBVNRequest.ProtoReflect.Descriptor instead.
func (*VerifyBVNRequest) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyBVNRequest) GetBvn() string {
	if x != nil {
		return x.Bvn
	}
	return ""
}

func (x *VerifyBVNRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *VerifyBVNRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type VerifyBVNResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verified      bool                   `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,4,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyBVNResponse) Reset() {
	*x = VerifyBVNResponse{}
	mi := &file_proto_compliance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyBVNResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyBVNResponse) ProtoMessage() {}

func (x *VerifyBVNResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyBVNResponse.ProtoReflect.Descriptor instead.
func (*VerifyBVNResponse) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyBVNResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *VerifyBVNResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VerifyBVNResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *VerifyBVNResponse) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

type VerifyNINRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nin           string                 `protobuf:"bytes,1,opt,name=nin,proto3" json:"nin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyNINRequest) Reset() {
	*x = VerifyNINRequest{}
	mi := &file_proto_compliance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyNINRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyNINRequest) ProtoMessage() {}

func (x *VerifyNINRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyNINRequest.ProtoReflect.Descriptor instead.
func (*VerifyNINRequest) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyNINRequest) GetNin() string {
	if x != nil {
		return x.Nin
	}
	return ""
}

type VerifyNINResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verified      bool                   `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyNINResponse) Reset() {
	*x = VerifyNINResponse{}
	mi := &file_proto_compliance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyNINResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyNINResponse) ProtoMessage() {}

func (x *VerifyNINResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyNINResponse.ProtoReflect.Descriptor instead.
func (*VerifyNINResponse) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyNINResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *VerifyNINResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_compliance_proto protoreflect.FileDescriptor

const file_proto_compliance_proto_rawDesc = "" +
	"\n" +
	"\x16proto/compliance.proto\x12\n" +
	"compliance\"`\n" +
	"\x10VerifyBVNRequest\x12\x10\n" +
	"\x03bvn\x18\x01 \x01(\tR\x03bvn\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\"\x8a\x01\n" +
	"\x11VerifyBVNResponse\x12\x1a\n" +
	"\bverified\x18\x01 \x01(\bR\bverified\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\"\n" +
	"\rdate_of_birth\x18\x04 \x01(\tR\vdateOfBirth\"$\n" +
	"\x10VerifyNINRequest\x12\x10\n" +
	"\x03nin\x18\x01 \x01(\tR\x03nin\"I\n" +
	"\x11VerifyNINResponse\x12\x1a\n" +
	"\bverified\x18\x01 \x01(\bR\bverified\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xa7\x01\n" +
	"\x11ComplianceService\x12H\n" +
	"\tVerifyBVN\x12\x1c.compliance.VerifyBVNRequest\x1a\x1d.compliance.VerifyBVNResponse\x12H\n" +
	"\tVerifyNIN\x12\x1c.compliance.VerifyNINRequest\x1a\x1d.compliance.VerifyNINResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_compliance_proto_rawDescOnce sync.Once
	file_proto_compliance_proto_rawDescData []byte
)

func file_proto_compliance_proto_rawDescGZIP() []byte {
	file_proto_compliance_proto_rawDescOnce.Do(func() {
		file_proto_compliance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_compliance_proto_rawDesc), len(file_proto_compliance_proto_rawDesc)))
	})
	return file_proto_compliance_proto_rawDescData
}

var file_proto_compliance_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_compliance_proto_goTypes = []any{
	(*VerifyBVNRequest)(nil),  // 0: compliance.VerifyBVNRequest
	(*VerifyBVNResponse)(nil), // 1: compliance.VerifyBVNResponse
	(*VerifyNINRequest)(nil),  // 2: compliance.VerifyNINRequest
	(*VerifyNINResponse)(nil), // 3: compliance.VerifyNINResponse
}
var file_proto_compliance_proto_depIdxs = []int32{
	0, // 0: compliance.ComplianceService.VerifyBVN:input_type -> compliance.VerifyBVNRequest
	2, // 1: compliance.ComplianceService.VerifyNIN:input_type -> compliance.VerifyNINRequest
	1, // 2: compliance.ComplianceService.VerifyBVN:output_type -> compliance.VerifyBVNResponse
	3, // 3: compliance.ComplianceService.VerifyNIN:output_type -> compliance.VerifyNINResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_compliance_proto_init() }
func file_proto_compliance_proto_init() {
	if File_proto_compliance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_compliance_proto_rawDesc), len(file_proto_compliance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_compliance_proto_goTypes,
		DependencyIndexes: file_proto_compliance_proto_depIdxs,
		MessageInfos:      file_proto_compliance_proto_msgTypes,
	}.Build()
	File_proto_compliance_proto = out.File
	file_proto_compliance_proto_goTypes = nil
	file_proto_compliance_proto_depIdxs = nil
}
