// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: bankone.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BankOneService_CreateAccountQuick_FullMethodName       = "/bankone.BankOneService/CreateAccountQuick"
	BankOneService_CreateCustomerAndAccount_FullMethodName = "/bankone.BankOneService/CreateCustomerAndAccount"
	BankOneService_GetBalance_FullMethodName               = "/bankone.BankOneService/GetBalance"
	BankOneService_GetTransactions_FullMethodName          = "/bankone.BankOneService/GetTransactions"
	BankOneService_AccountEnquiry_FullMethodName           = "/bankone.BankOneService/AccountEnquiry"
	BankOneService_SetPND_FullMethodName                   = "/bankone.BankOneService/SetPND"
	BankOneService_SetLien_FullMethodName                  = "/bankone.BankOneService/SetLien"
	BankOneService_GetBVNDetails_FullMethodName            = "/bankone.BankOneService/GetBVNDetails"
	BankOneService_InterbankTransfer_FullMethodName        = "/bankone.BankOneService/InterbankTransfer"
	BankOneService_GetOtherBankList_FullMethodName         = "/bankone.BankOneService/GetOtherBankList"
)

// BankOneServiceClient is the client API for BankOneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BankOneServiceClient interface {
	CreateAccountQuick(ctx context.Context, in *CreateAccountQuickRequest, opts ...grpc.CallOption) (*BankOneResponse, error)
	CreateCustomerAndAccount(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*BankOneResponse, error)
	GetBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
	GetTransactions(ctx context.Context, in *TransactionsRequest, opts ...grpc.CallOption) (*TransactionsResponse, error)
	AccountEnquiry(ctx context.Context, in *AccountEnquiryRequest, opts ...grpc.CallOption) (*BankOneResponse, error)
	SetPND(ctx context.Context, in *PNDRequest, opts ...grpc.CallOption) (*BankOneResponse, error)
	SetLien(ctx context.Context, in *LienRequest, opts ...grpc.CallOption) (*BankOneResponse, error)
	GetBVNDetails(ctx context.Context, in *BVNRequest, opts ...grpc.CallOption) (*BankOneResponse, error)
	InterbankTransfer(ctx context.Context, in *InterbankTransferRequest, opts ...grpc.CallOption) (*BankOneResponse, error)
	GetOtherBankList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BankOneResponse, error)
}

type bankOneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBankOneServiceClient(cc grpc.ClientConnInterface) BankOneServiceClient {
	return &bankOneServiceClient{cc}
}

func (c *bankOneServiceClient) CreateAccountQuick(ctx context.Context, in *CreateAccountQuickRequest, opts ...grpc.CallOption) (*BankOneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BankOneResponse)
	err := c.cc.Invoke(ctx, BankOneService_CreateAccountQuick_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankOneServiceClient) CreateCustomerAndAccount(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*BankOneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BankOneResponse)
	err := c.cc.Invoke(ctx, BankOneService_CreateCustomerAndAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankOneServiceClient) GetBalance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, BankOneService_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankOneServiceClient) GetTransactions(ctx context.Context, in *TransactionsRequest, opts ...grpc.CallOption) (*TransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransactionsResponse)
	err := c.cc.Invoke(ctx, BankOneService_GetTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankOneServiceClient) AccountEnquiry(ctx context.Context, in *AccountEnquiryRequest, opts ...grpc.CallOption) (*BankOneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BankOneResponse)
	err := c.cc.Invoke(ctx, BankOneService_AccountEnquiry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankOneServiceClient) SetPND(ctx context.Context, in *PNDRequest, opts ...grpc.CallOption) (*BankOneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BankOneResponse)
	err := c.cc.Invoke(ctx, BankOneService_SetPND_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankOneServiceClient) SetLien(ctx context.Context, in *LienRequest, opts ...grpc.CallOption) (*BankOneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BankOneResponse)
	err := c.cc.Invoke(ctx, BankOneService_SetLien_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankOneServiceClient) GetBVNDetails(ctx context.Context, in *BVNRequest, opts ...grpc.CallOption) (*BankOneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BankOneResponse)
	err := c.cc.Invoke(ctx, BankOneService_GetBVNDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankOneServiceClient) InterbankTransfer(ctx context.Context, in *InterbankTransferRequest, opts ...grpc.CallOption) (*BankOneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BankOneResponse)
	err := c.cc.Invoke(ctx, BankOneService_InterbankTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankOneServiceClient) GetOtherBankList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BankOneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BankOneResponse)
	err := c.cc.Invoke(ctx, BankOneService_GetOtherBankList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BankOneServiceServer is the server API for BankOneService service.
// All implementations must embed UnimplementedBankOneServiceServer
// for forward compatibility.
type BankOneServiceServer interface {
	CreateAccountQuick(context.Context, *CreateAccountQuickRequest) (*BankOneResponse, error)
	CreateCustomerAndAccount(context.Context, *CreateCustomerRequest) (*BankOneResponse, error)
	GetBalance(context.Context, *BalanceRequest) (*BalanceResponse, error)
	GetTransactions(context.Context, *TransactionsRequest) (*TransactionsResponse, error)
	AccountEnquiry(context.Context, *AccountEnquiryRequest) (*BankOneResponse, error)
	SetPND(context.Context, *PNDRequest) (*BankOneResponse, error)
	SetLien(context.Context, *LienRequest) (*BankOneResponse, error)
	GetBVNDetails(context.Context, *BVNRequest) (*BankOneResponse, error)
	InterbankTransfer(context.Context, *InterbankTransferRequest) (*BankOneResponse, error)
	GetOtherBankList(context.Context, *Empty) (*BankOneResponse, error)
	mustEmbedUnimplementedBankOneServiceServer()
}

// UnimplementedBankOneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBankOneServiceServer struct{}

func (UnimplementedBankOneServiceServer) CreateAccountQuick(context.Context, *CreateAccountQuickRequest) (*BankOneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAccountQuick not implemented")
}
func (UnimplementedBankOneServiceServer) CreateCustomerAndAccount(context.Context, *CreateCustomerRequest) (*BankOneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCustomerAndAccount not implemented")
}
func (UnimplementedBankOneServiceServer) GetBalance(context.Context, *BalanceRequest) (*BalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedBankOneServiceServer) GetTransactions(context.Context, *TransactionsRequest) (*TransactionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransactions not implemented")
}
func (UnimplementedBankOneServiceServer) AccountEnquiry(context.Context, *AccountEnquiryRequest) (*BankOneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AccountEnquiry not implemented")
}
func (UnimplementedBankOneServiceServer) SetPND(context.Context, *PNDRequest) (*BankOneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPND not implemented")
}
func (UnimplementedBankOneServiceServer) SetLien(context.Context, *LienRequest) (*BankOneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetLien not implemented")
}
func (UnimplementedBankOneServiceServer) GetBVNDetails(context.Context, *BVNRequest) (*BankOneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBVNDetails not implemented")
}
func (UnimplementedBankOneServiceServer) InterbankTransfer(context.Context, *InterbankTransferRequest) (*BankOneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InterbankTransfer not implemented")
}
func (UnimplementedBankOneServiceServer) GetOtherBankList(context.Context, *Empty) (*BankOneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOtherBankList not implemented")
}
func (UnimplementedBankOneServiceServer) mustEmbedUnimplementedBankOneServiceServer() {}
func (UnimplementedBankOneServiceServer) testEmbeddedByValue()                        {}

// UnsafeBankOneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BankOneServiceServer will
// result in compilation errors.
type UnsafeBankOneServiceServer interface {
	mustEmbedUnimplementedBankOneServiceServer()
}

func RegisterBankOneServiceServer(s grpc.ServiceRegistrar, srv BankOneServiceServer) {
	// If the following call panics, it indicates UnimplementedBankOneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BankOneService_ServiceDesc, srv)
}

func _BankOneService_CreateAccountQuick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountQuickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankOneServiceServer).CreateAccountQuick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankOneService_CreateAccountQuick_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankOneServiceServer).CreateAccountQuick(ctx, req.(*CreateAccountQuickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankOneService_CreateCustomerAndAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankOneServiceServer).CreateCustomerAndAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankOneService_CreateCustomerAndAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankOneServiceServer).CreateCustomerAndAccount(ctx, req.(*CreateCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankOneService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankOneServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankOneService_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankOneServiceServer).GetBalance(ctx, req.(*BalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankOneService_GetTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankOneServiceServer).GetTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankOneService_GetTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankOneServiceServer).GetTransactions(ctx, req.(*TransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankOneService_AccountEnquiry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountEnquiryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankOneServiceServer).AccountEnquiry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankOneService_AccountEnquiry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankOneServiceServer).AccountEnquiry(ctx, req.(*AccountEnquiryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankOneService_SetPND_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PNDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankOneServiceServer).SetPND(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankOneService_SetPND_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankOneServiceServer).SetPND(ctx, req.(*PNDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankOneService_SetLien_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LienRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankOneServiceServer).SetLien(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankOneService_SetLien_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankOneServiceServer).SetLien(ctx, req.(*LienRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankOneService_GetBVNDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BVNRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankOneServiceServer).GetBVNDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankOneService_GetBVNDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankOneServiceServer).GetBVNDetails(ctx, req.(*BVNRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankOneService_InterbankTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterbankTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankOneServiceServer).InterbankTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankOneService_InterbankTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankOneServiceServer).InterbankTransfer(ctx, req.(*InterbankTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankOneService_GetOtherBankList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankOneServiceServer).GetOtherBankList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankOneService_GetOtherBankList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankOneServiceServer).GetOtherBankList(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// BankOneService_ServiceDesc is the grpc.ServiceDesc for BankOneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BankOneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bankone.BankOneService",
	HandlerType: (*BankOneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccountQuick",
			Handler:    _BankOneService_CreateAccountQuick_Handler,
		},
		{
			MethodName: "CreateCustomerAndAccount",
			Handler:    _BankOneService_CreateCustomerAndAccount_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _BankOneService_GetBalance_Handler,
		},
		{
			MethodName: "GetTransactions",
			Handler:    _BankOneService_GetTransactions_Handler,
		},
		{
			MethodName: "AccountEnquiry",
			Handler:    _BankOneService_AccountEnquiry_Handler,
		},
		{
			MethodName: "SetPND",
			Handler:    _BankOneService_SetPND_Handler,
		},
		{
			MethodName: "SetLien",
			Handler:    _BankOneService_SetLien_Handler,
		},
		{
			MethodName: "GetBVNDetails",
			Handler:    _BankOneService_GetBVNDetails_Handler,
		},
		{
			MethodName: "InterbankTransfer",
			Handler:    _BankOneService_InterbankTransfer_Handler,
		},
		{
			MethodName: "GetOtherBankList",
			Handler:    _BankOneService_GetOtherBankList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bankone.proto",
}
