import { MigrationInterface, QueryRunner } from "typeorm";

export class AddAllEntities1753952214817 implements MigrationInterface {
  name = "AddAllEntities1753952214803";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE customer_management (
        id int NOT NULL AUTO_INCREMENT,
        title_cd text NOT NULL,
        last_name varchar(20) NOT NULL,
        first_name varchar(20) NOT NULL,
        other_names varchar(20) NOT NULL,
        gender_cd text NOT NULL,
        marital_status_cd text NOT NULL,
        birth_date text NOT NULL,
        mother_maiden_name varchar(20) NOT NULL,
        wedding_anniversary_date text NOT NULL,
        nationality_cd text NOT NULL,
        mobile_phone_no text NOT NULL,
        alternate_phone_no text NOT NULL,
        primary_email_address varchar(20) NOT NULL,
        alternate_email_address text NOT NULL,
        address_street text NOT NULL,
        address_city text NOT NULL,
        address_state_cd text NOT NULL,
        address_country_cd text NOT NULL,
        address_zip_code text NOT NULL,
        occupation text NOT NULL,
        employer_name text NOT NULL,
        employment_job_title text NOT NULL,
        employer_reference text NOT NULL,
        employer_address_street text NOT NULL,
        employer_address_city text NOT NULL,
        employer_address_country_cd text NOT NULL,
        estimated_annual_income text NOT NULL,
        bank_cd text NOT NULL,
        bank_account_name text NOT NULL,
        bank_account_no text NOT NULL,
        bank_branch_name text NOT NULL,
        bank_address_details text NOT NULL,
        bank_bvn_no text NOT NULL,
        next_of_kin_title_cd text NOT NULL,
        next_of_kin_last_name text NOT NULL,
        next_of_kin_first_name text NOT NULL,
        next_of_kin_other_names text NOT NULL,
        next_of_kin_gender_cd text NOT NULL,
        next_of_kin_relationship_cd text NOT NULL,
        next_of_kin_telephone text NOT NULL,
        next_of_kin_email_address text NOT NULL,
        next_of_kin_address_street text NOT NULL,
        next_of_kin_address_city text NOT NULL,
        next_of_kin_address_country_cd text NOT NULL,
        next_of_kin_address_zip_code text NOT NULL,
        identity_doc_type_cd text NOT NULL,
        identity_doc_name text NOT NULL,
        identity_doc_no text NOT NULL,
        identity_doc_issue_date text NOT NULL,
        identity_doc_expiry_date text NOT NULL,
        identity_doc_issue_authority text NOT NULL,
        location_cd text NOT NULL,
        external_reference1 text NOT NULL,
        external_reference2 text NOT NULL,
        retain_customer_id text NOT NULL,
        external_crm_id text NOT NULL,
        officer_id text NOT NULL,
        createdAt timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        updatedAt timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
        PRIMARY KEY (id)
      ) ENGINE=InnoDB
    `);
    await queryRunner.query(`
      CREATE TABLE corporate_customer (
        id int NOT NULL AUTO_INCREMENT,
        corporate_type_dm text NOT NULL,
        organization_name varchar(255) NOT NULL,
        registration_number varchar(10) NOT NULL,
        registration_date varchar(10) NOT NULL,
        registration_country_cd varchar(20) NOT NULL,
        tax_identification_number varchar(10) NOT NULL,
        business_sector_cd varchar(20) NOT NULL,
        location_cd varchar(20) NOT NULL,
        address_street varchar(100) NOT NULL,
        address_city text NOT NULL,
        address_state_cd text NOT NULL,
        address_country_cd text NOT NULL,
        address_zip_code text NOT NULL,
        primary_phone_no text NOT NULL,
        alternate_phone_no text NOT NULL,
        primary_email_address text NOT NULL,
        alternate_email_address text NOT NULL,
        website_address text NOT NULL,
        twitter_address text NOT NULL,
        bank_cd text NOT NULL,
        bank_account_name text NOT NULL,
        bank_account_no text NOT NULL,
        bank_branch_name text NOT NULL,
        bank_address_details text NOT NULL,
        bank_bvn_no text NOT NULL,
        signatory1_yn text NOT NULL,
        signatory1_account_no text NOT NULL,
        signatory1_bank_name_cd text NOT NULL,
        signatory1_employer_address text NOT NULL,
        signatory1_employer_name text NOT NULL,
        signatory1_employer_phone_no text NOT NULL,
        signatory1_lga_cd text NOT NULL,
        signatory1_marital_status text NOT NULL,
        signatory1_mother_maiden_name text NOT NULL,
        signatory1_nin text NOT NULL,
        signatory1_occupation text NOT NULL,
        signatory1_pep_yn text NOT NULL,
        signatory1_place_of_birth text NOT NULL,
        signatory1_state_of_origin_cd text NOT NULL,
        signatory1_title_cd text NOT NULL,
        signatory1_last_name text NOT NULL,
        signatory1_first_name text NOT NULL,
        signatory1_other_names text NOT NULL,
        signatory1_gender_cd text NOT NULL,
        signatory1_birth_date text NOT NULL,
        signatory1_nationality_cd text NOT NULL,
        signatory1_job_title text NOT NULL,
        signatory1_telephone text NOT NULL,
        signatory1_email_address text NOT NULL,
        signatory1_address_street text NOT NULL,
        signatory1_address_city text NOT NULL,
        signatory1_address_country_cd text NOT NULL,
        signatory1_bvn_number text NOT NULL,
        signatory1_class text NOT NULL,
        signatory2_yn text NOT NULL,
        signatory2_account_no text NOT NULL,
        signatory2_bank_name_cd text NOT NULL,
        signatory2_employer_address text NOT NULL,
        signatory2_employer_name text NOT NULL,
        signatory2_employer_phone_no text NOT NULL,
        signatory2_lga_cd text NOT NULL,
        signatory2_marital_status text NOT NULL,
        signatory2_mother_maiden_name text NOT NULL,
        signatory2_nin text NOT NULL,
        signatory2_occupation text NOT NULL,
        signatory2_pep_yn text NOT NULL,
        signatory2_place_of_birth text NOT NULL,
        signatory2_state_of_origin_cd text NOT NULL,
        signatory2_title_cd text NOT NULL,
        signatory2_last_name text NOT NULL,
        signatory2_first_name text NOT NULL,
        signatory2_other_names text NOT NULL,
        signatory2_gender_cd text NOT NULL,
        signatory2_birth_date text NOT NULL,
        signatory2_nationality_cd text NOT NULL,
        signatory2_job_title text NOT NULL,
        signatory2_telephone text NOT NULL,
        signatory2_email_address text NOT NULL,
        signatory2_address_street text NOT NULL,
        signatory2_address_city text NOT NULL,
        signatory2_address_country_cd text NOT NULL,
        signatory2_bvn_number text NOT NULL,
        signatory2_class text NOT NULL,
        signatory3_yn text NOT NULL,
        signatory3_account_no text NOT NULL,
        signatory3_bank_name_cd text NOT NULL,
        signatory3_employer_address text NOT NULL,
        signatory3_employer_name text NOT NULL,
        signatory3_employer_phone_no text NOT NULL,
        signatory3_lga_cd text NOT NULL,
        signatory3_marital_status text NOT NULL,
        signatory3_mother_maiden_name text NOT NULL,
        signatory3_nin text NOT NULL,
        signatory3_occupation text NOT NULL,
        signatory3_pep_yn text NOT NULL,
        signatory3_place_of_birth text NOT NULL,
        signatory3_state_of_origin_cd text NOT NULL,
        signatory3_title_cd text NOT NULL,
        signatory3_last_name text NOT NULL,
        signatory3_first_name text NOT NULL,
        signatory3_other_names text NOT NULL,
        signatory3_gender_cd text NOT NULL,
        signatory3_birth_date text NOT NULL,
        signatory3_nationality_cd text NOT NULL,
        signatory3_job_title text NOT NULL,
        signatory3_telephone text NOT NULL,
        signatory3_email_address text NOT NULL,
        signatory3_address_street text NOT NULL,
        signatory3_address_city text NOT NULL,
        signatory3_address_country_cd text NOT NULL,
        signatory3_bvn_number text NOT NULL,
        signatory3_class text NOT NULL,
        external_reference1 text NOT NULL,
        external_reference2 text NOT NULL,
        retain_customer_id text NOT NULL,
        customer_remarks text NOT NULL,
        external_crm_id text NOT NULL,
        createdAt timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        updatedAt timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
        PRIMARY KEY (id)
      ) ENGINE=InnoDB
    `);
    await queryRunner.query(`
      CREATE TABLE symplus_api_request (
        id int NOT NULL AUTO_INCREMENT,
        api_url varchar(255) NOT NULL,
        request_ref varchar(255) NULL,
        request_body text NULL,
        api_response text NULL,
        verify_response text NULL,
        webhook_response text NULL,
        call_type enum('POST','GET','PATCH','PUT','DELETE') NULL,
        call_category enum('CUSTOMER_MANAGEMENT','CUSTOMER_ACCOUNTS','STOCK_BROKING','MUTUAL_FUNDS','GENERAL') NULL,
        response_type enum('Normal API Response','webhook_response','verify_response') NOT NULL,
        createdAt timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        updatedAt timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
        PRIMARY KEY (id)
      ) ENGINE=InnoDB
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE event_handler`);
    await queryRunner.query(`DROP TABLE event_listener`);
    await queryRunner.query(`DROP TABLE push`);
    await queryRunner.query(`DROP TABLE notifier`);
    await queryRunner.query(`DROP TABLE reporting`);
    await queryRunner.query(`DROP TABLE sys_auth`);
    await queryRunner.query(`DROP TABLE audit_logger`);
    await queryRunner.query(`DROP TABLE notification`);
    await queryRunner.query(`DROP TABLE customer_management`);
    await queryRunner.query(`DROP TABLE corporate_customer`);
    await queryRunner.query(`DROP TABLE symplus_api_request`);
  }
}
