syntax = "proto3";

package bankone;

option go_package = "github.com/gdl/bankone-connector/proto";

service BankOneService {
  rpc CreateAccountQuick (CreateAccountQuickRequest) returns (BankOneResponse);
  rpc CreateCustomerAndAccount (CreateCustomerRequest) returns (BankOneResponse);
  rpc GetBalance (BalanceRequest) returns (BalanceResponse);
  rpc GetTransactions (TransactionsRequest) returns (TransactionsResponse);
  rpc AccountEnquiry (AccountEnquiryRequest) returns (BankOneResponse);
  rpc SetPND (PNDRequest) returns (BankOneResponse);
  rpc SetLien (LienRequest) returns (BankOneResponse);
  rpc GetBVNDetails (BVNRequest) returns (BankOneResponse);
  rpc InterbankTransfer (InterbankTransferRequest) returns (BankOneResponse);
  rpc TransactionStatusQuery (TSQRequest) returns (BankOneResponse);
  rpc GetOtherBankList (Empty) returns (BankOneResponse);
}

message Empty {}

message InterbankTransferRequest {
  string amount = 1; // in Naira, will be converted to Kobo in connector
  string payer_account_number = 2;
  string payer_name = 3;
  string receiver_bank_code = 4;
  string receiver_account_number = 5;
  string receiver_name = 6;
  string receiver_phone_number = 7;
  string receiver_account_type = 8;
  string receiver_kyc = 9;
  string receiver_bvn = 10;
  string narration = 11;
  string reference = 12;
}

message TSQRequest {
  string retrieval_reference = 1;
  string transaction_date = 2; // YYYY-MM-DD
  string transaction_type = 3;
  string amount = 4; // in Naira
}

message CreateAccountQuickRequest {
  string first_name = 1;
  string last_name = 2;
  string email = 3;
  string phone = 4;
  string account_type = 5;
}

message CreateCustomerRequest {
  string first_name = 1;
  string last_name = 2;
  string phone = 3;
  string email = 4;
}

message BalanceRequest {
  string account_number = 1;
}

message BalanceResponse {
  bool success = 1;
  double balance = 2;
  string message = 3;
}

message TransactionsRequest {
  string account_number = 1;
  string from_date = 2;
  string to_date = 3;
}

message TransactionsResponse {
  bool success = 1;
  repeated TransactionInfo transactions = 2;
}

message TransactionInfo {
  string amount = 1;
  string date = 2;
  string description = 3;
  string reference = 4;
}

message AccountEnquiryRequest {
  string account_number = 1;
}

message PNDRequest {
  string account_number = 2;
  bool active = 3;
}

message LienRequest {
  string account_number = 1;
  double amount = 2;
  bool active = 3;
}

message BVNRequest {
  string bvn = 1;
}

message BankOneResponse {
  bool success = 1;
  string message = 2;
  string data = 3; // JSON encoded response from BankOne
}
