// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: user.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdentityService_Register_FullMethodName                 = "/identity.IdentityService/Register"
	IdentityService_Login_FullMethodName                    = "/identity.IdentityService/Login"
	IdentityService_VerifyOTP_FullMethodName                = "/identity.IdentityService/VerifyOTP"
	IdentityService_GetProfile_FullMethodName               = "/identity.IdentityService/GetProfile"
	IdentityService_ForgotPassword_FullMethodName           = "/identity.IdentityService/ForgotPassword"
	IdentityService_CreateRole_FullMethodName               = "/identity.IdentityService/CreateRole"
	IdentityService_AssignRole_FullMethodName               = "/identity.IdentityService/AssignRole"
	IdentityService_GetRoles_FullMethodName                 = "/identity.IdentityService/GetRoles"
	IdentityService_CreateBusinessUnit_FullMethodName       = "/identity.IdentityService/CreateBusinessUnit"
	IdentityService_GetBusinessUnits_FullMethodName         = "/identity.IdentityService/GetBusinessUnits"
	IdentityService_UpdateBusinessUnit_FullMethodName       = "/identity.IdentityService/UpdateBusinessUnit"
	IdentityService_DeleteBusinessUnit_FullMethodName       = "/identity.IdentityService/DeleteBusinessUnit"
	IdentityService_SetPIN_FullMethodName                   = "/identity.IdentityService/SetPIN"
	IdentityService_VerifyPIN_FullMethodName                = "/identity.IdentityService/VerifyPIN"
	IdentityService_CheckAccountStatus_FullMethodName       = "/identity.IdentityService/CheckAccountStatus"
	IdentityService_UpdateKYCLevel_FullMethodName           = "/identity.IdentityService/UpdateKYCLevel"
	IdentityService_GetKYCStatus_FullMethodName             = "/identity.IdentityService/GetKYCStatus"
	IdentityService_GetSecurityQuestions_FullMethodName     = "/identity.IdentityService/GetSecurityQuestions"
	IdentityService_SetUserSecurityQuestions_FullMethodName = "/identity.IdentityService/SetUserSecurityQuestions"
	IdentityService_VerifySecurityAnswer_FullMethodName     = "/identity.IdentityService/VerifySecurityAnswer"
	IdentityService_ExportData_FullMethodName               = "/identity.IdentityService/ExportData"
	IdentityService_DeleteAccount_FullMethodName            = "/identity.IdentityService/DeleteAccount"
	IdentityService_UpdateConsent_FullMethodName            = "/identity.IdentityService/UpdateConsent"
)

// IdentityServiceClient is the client API for IdentityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdentityServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	VerifyOTP(ctx context.Context, in *VerifyOTPRequest, opts ...grpc.CallOption) (*VerifyOTPResponse, error)
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error)
	ForgotPassword(ctx context.Context, in *ForgotPasswordRequest, opts ...grpc.CallOption) (*ForgotPasswordResponse, error)
	// RBAC Management
	CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*CreateRoleResponse, error)
	AssignRole(ctx context.Context, in *AssignRoleRequest, opts ...grpc.CallOption) (*AssignRoleResponse, error)
	GetRoles(ctx context.Context, in *GetRolesRequest, opts ...grpc.CallOption) (*GetRolesResponse, error)
	// Business Unit & Branch Management
	CreateBusinessUnit(ctx context.Context, in *CreateBusinessUnitRequest, opts ...grpc.CallOption) (*CreateBusinessUnitResponse, error)
	GetBusinessUnits(ctx context.Context, in *GetBusinessUnitsRequest, opts ...grpc.CallOption) (*GetBusinessUnitsResponse, error)
	UpdateBusinessUnit(ctx context.Context, in *UpdateBusinessUnitRequest, opts ...grpc.CallOption) (*UpdateBusinessUnitResponse, error)
	DeleteBusinessUnit(ctx context.Context, in *DeleteBusinessUnitRequest, opts ...grpc.CallOption) (*DeleteBusinessUnitResponse, error)
	// Security & PINs
	SetPIN(ctx context.Context, in *SetPINRequest, opts ...grpc.CallOption) (*SetPINResponse, error)
	VerifyPIN(ctx context.Context, in *VerifyPINRequest, opts ...grpc.CallOption) (*VerifyPINResponse, error)
	CheckAccountStatus(ctx context.Context, in *CheckStatusRequest, opts ...grpc.CallOption) (*CheckStatusResponse, error)
	// KYC Management
	UpdateKYCLevel(ctx context.Context, in *UpdateKYCRequest, opts ...grpc.CallOption) (*UpdateKYCResponse, error)
	GetKYCStatus(ctx context.Context, in *GetKYCStatusRequest, opts ...grpc.CallOption) (*GetKYCStatusResponse, error)
	// Security Questions
	GetSecurityQuestions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SecurityQuestionsResponse, error)
	SetUserSecurityQuestions(ctx context.Context, in *SetUserQuestionsRequest, opts ...grpc.CallOption) (*SetUserQuestionsResponse, error)
	VerifySecurityAnswer(ctx context.Context, in *VerifyAnswerRequest, opts ...grpc.CallOption) (*VerifyAnswerResponse, error)
	// NDPR/GDPR Compliance
	ExportData(ctx context.Context, in *ExportDataRequest, opts ...grpc.CallOption) (*ExportDataResponse, error)
	DeleteAccount(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*DeleteAccountResponse, error)
	UpdateConsent(ctx context.Context, in *UpdateConsentRequest, opts ...grpc.CallOption) (*UpdateConsentResponse, error)
}

type identityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityServiceClient(cc grpc.ClientConnInterface) IdentityServiceClient {
	return &identityServiceClient{cc}
}

func (c *identityServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, IdentityService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, IdentityService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) VerifyOTP(ctx context.Context, in *VerifyOTPRequest, opts ...grpc.CallOption) (*VerifyOTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyOTPResponse)
	err := c.cc.Invoke(ctx, IdentityService_VerifyOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfileResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) ForgotPassword(ctx context.Context, in *ForgotPasswordRequest, opts ...grpc.CallOption) (*ForgotPasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForgotPasswordResponse)
	err := c.cc.Invoke(ctx, IdentityService_ForgotPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*CreateRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRoleResponse)
	err := c.cc.Invoke(ctx, IdentityService_CreateRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) AssignRole(ctx context.Context, in *AssignRoleRequest, opts ...grpc.CallOption) (*AssignRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignRoleResponse)
	err := c.cc.Invoke(ctx, IdentityService_AssignRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetRoles(ctx context.Context, in *GetRolesRequest, opts ...grpc.CallOption) (*GetRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRolesResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) CreateBusinessUnit(ctx context.Context, in *CreateBusinessUnitRequest, opts ...grpc.CallOption) (*CreateBusinessUnitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBusinessUnitResponse)
	err := c.cc.Invoke(ctx, IdentityService_CreateBusinessUnit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetBusinessUnits(ctx context.Context, in *GetBusinessUnitsRequest, opts ...grpc.CallOption) (*GetBusinessUnitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBusinessUnitsResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetBusinessUnits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) UpdateBusinessUnit(ctx context.Context, in *UpdateBusinessUnitRequest, opts ...grpc.CallOption) (*UpdateBusinessUnitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBusinessUnitResponse)
	err := c.cc.Invoke(ctx, IdentityService_UpdateBusinessUnit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) DeleteBusinessUnit(ctx context.Context, in *DeleteBusinessUnitRequest, opts ...grpc.CallOption) (*DeleteBusinessUnitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBusinessUnitResponse)
	err := c.cc.Invoke(ctx, IdentityService_DeleteBusinessUnit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) SetPIN(ctx context.Context, in *SetPINRequest, opts ...grpc.CallOption) (*SetPINResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPINResponse)
	err := c.cc.Invoke(ctx, IdentityService_SetPIN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) VerifyPIN(ctx context.Context, in *VerifyPINRequest, opts ...grpc.CallOption) (*VerifyPINResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyPINResponse)
	err := c.cc.Invoke(ctx, IdentityService_VerifyPIN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) CheckAccountStatus(ctx context.Context, in *CheckStatusRequest, opts ...grpc.CallOption) (*CheckStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckStatusResponse)
	err := c.cc.Invoke(ctx, IdentityService_CheckAccountStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) UpdateKYCLevel(ctx context.Context, in *UpdateKYCRequest, opts ...grpc.CallOption) (*UpdateKYCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateKYCResponse)
	err := c.cc.Invoke(ctx, IdentityService_UpdateKYCLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetKYCStatus(ctx context.Context, in *GetKYCStatusRequest, opts ...grpc.CallOption) (*GetKYCStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKYCStatusResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetKYCStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetSecurityQuestions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SecurityQuestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecurityQuestionsResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetSecurityQuestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) SetUserSecurityQuestions(ctx context.Context, in *SetUserQuestionsRequest, opts ...grpc.CallOption) (*SetUserQuestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetUserQuestionsResponse)
	err := c.cc.Invoke(ctx, IdentityService_SetUserSecurityQuestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) VerifySecurityAnswer(ctx context.Context, in *VerifyAnswerRequest, opts ...grpc.CallOption) (*VerifyAnswerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyAnswerResponse)
	err := c.cc.Invoke(ctx, IdentityService_VerifySecurityAnswer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) ExportData(ctx context.Context, in *ExportDataRequest, opts ...grpc.CallOption) (*ExportDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportDataResponse)
	err := c.cc.Invoke(ctx, IdentityService_ExportData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) DeleteAccount(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*DeleteAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAccountResponse)
	err := c.cc.Invoke(ctx, IdentityService_DeleteAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) UpdateConsent(ctx context.Context, in *UpdateConsentRequest, opts ...grpc.CallOption) (*UpdateConsentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateConsentResponse)
	err := c.cc.Invoke(ctx, IdentityService_UpdateConsent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServiceServer is the server API for IdentityService service.
// All implementations must embed UnimplementedIdentityServiceServer
// for forward compatibility.
type IdentityServiceServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	VerifyOTP(context.Context, *VerifyOTPRequest) (*VerifyOTPResponse, error)
	GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error)
	ForgotPassword(context.Context, *ForgotPasswordRequest) (*ForgotPasswordResponse, error)
	// RBAC Management
	CreateRole(context.Context, *CreateRoleRequest) (*CreateRoleResponse, error)
	AssignRole(context.Context, *AssignRoleRequest) (*AssignRoleResponse, error)
	GetRoles(context.Context, *GetRolesRequest) (*GetRolesResponse, error)
	// Business Unit & Branch Management
	CreateBusinessUnit(context.Context, *CreateBusinessUnitRequest) (*CreateBusinessUnitResponse, error)
	GetBusinessUnits(context.Context, *GetBusinessUnitsRequest) (*GetBusinessUnitsResponse, error)
	UpdateBusinessUnit(context.Context, *UpdateBusinessUnitRequest) (*UpdateBusinessUnitResponse, error)
	DeleteBusinessUnit(context.Context, *DeleteBusinessUnitRequest) (*DeleteBusinessUnitResponse, error)
	// Security & PINs
	SetPIN(context.Context, *SetPINRequest) (*SetPINResponse, error)
	VerifyPIN(context.Context, *VerifyPINRequest) (*VerifyPINResponse, error)
	CheckAccountStatus(context.Context, *CheckStatusRequest) (*CheckStatusResponse, error)
	// KYC Management
	UpdateKYCLevel(context.Context, *UpdateKYCRequest) (*UpdateKYCResponse, error)
	GetKYCStatus(context.Context, *GetKYCStatusRequest) (*GetKYCStatusResponse, error)
	// Security Questions
	GetSecurityQuestions(context.Context, *Empty) (*SecurityQuestionsResponse, error)
	SetUserSecurityQuestions(context.Context, *SetUserQuestionsRequest) (*SetUserQuestionsResponse, error)
	VerifySecurityAnswer(context.Context, *VerifyAnswerRequest) (*VerifyAnswerResponse, error)
	// NDPR/GDPR Compliance
	ExportData(context.Context, *ExportDataRequest) (*ExportDataResponse, error)
	DeleteAccount(context.Context, *DeleteAccountRequest) (*DeleteAccountResponse, error)
	UpdateConsent(context.Context, *UpdateConsentRequest) (*UpdateConsentResponse, error)
	mustEmbedUnimplementedIdentityServiceServer()
}

// UnimplementedIdentityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityServiceServer struct{}

func (UnimplementedIdentityServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedIdentityServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedIdentityServiceServer) VerifyOTP(context.Context, *VerifyOTPRequest) (*VerifyOTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyOTP not implemented")
}
func (UnimplementedIdentityServiceServer) GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedIdentityServiceServer) ForgotPassword(context.Context, *ForgotPasswordRequest) (*ForgotPasswordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForgotPassword not implemented")
}
func (UnimplementedIdentityServiceServer) CreateRole(context.Context, *CreateRoleRequest) (*CreateRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRole not implemented")
}
func (UnimplementedIdentityServiceServer) AssignRole(context.Context, *AssignRoleRequest) (*AssignRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignRole not implemented")
}
func (UnimplementedIdentityServiceServer) GetRoles(context.Context, *GetRolesRequest) (*GetRolesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoles not implemented")
}
func (UnimplementedIdentityServiceServer) CreateBusinessUnit(context.Context, *CreateBusinessUnitRequest) (*CreateBusinessUnitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBusinessUnit not implemented")
}
func (UnimplementedIdentityServiceServer) GetBusinessUnits(context.Context, *GetBusinessUnitsRequest) (*GetBusinessUnitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBusinessUnits not implemented")
}
func (UnimplementedIdentityServiceServer) UpdateBusinessUnit(context.Context, *UpdateBusinessUnitRequest) (*UpdateBusinessUnitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBusinessUnit not implemented")
}
func (UnimplementedIdentityServiceServer) DeleteBusinessUnit(context.Context, *DeleteBusinessUnitRequest) (*DeleteBusinessUnitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBusinessUnit not implemented")
}
func (UnimplementedIdentityServiceServer) SetPIN(context.Context, *SetPINRequest) (*SetPINResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPIN not implemented")
}
func (UnimplementedIdentityServiceServer) VerifyPIN(context.Context, *VerifyPINRequest) (*VerifyPINResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyPIN not implemented")
}
func (UnimplementedIdentityServiceServer) CheckAccountStatus(context.Context, *CheckStatusRequest) (*CheckStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAccountStatus not implemented")
}
func (UnimplementedIdentityServiceServer) UpdateKYCLevel(context.Context, *UpdateKYCRequest) (*UpdateKYCResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateKYCLevel not implemented")
}
func (UnimplementedIdentityServiceServer) GetKYCStatus(context.Context, *GetKYCStatusRequest) (*GetKYCStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKYCStatus not implemented")
}
func (UnimplementedIdentityServiceServer) GetSecurityQuestions(context.Context, *Empty) (*SecurityQuestionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSecurityQuestions not implemented")
}
func (UnimplementedIdentityServiceServer) SetUserSecurityQuestions(context.Context, *SetUserQuestionsRequest) (*SetUserQuestionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetUserSecurityQuestions not implemented")
}
func (UnimplementedIdentityServiceServer) VerifySecurityAnswer(context.Context, *VerifyAnswerRequest) (*VerifyAnswerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifySecurityAnswer not implemented")
}
func (UnimplementedIdentityServiceServer) ExportData(context.Context, *ExportDataRequest) (*ExportDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportData not implemented")
}
func (UnimplementedIdentityServiceServer) DeleteAccount(context.Context, *DeleteAccountRequest) (*DeleteAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAccount not implemented")
}
func (UnimplementedIdentityServiceServer) UpdateConsent(context.Context, *UpdateConsentRequest) (*UpdateConsentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateConsent not implemented")
}
func (UnimplementedIdentityServiceServer) mustEmbedUnimplementedIdentityServiceServer() {}
func (UnimplementedIdentityServiceServer) testEmbeddedByValue()                         {}

// UnsafeIdentityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityServiceServer will
// result in compilation errors.
type UnsafeIdentityServiceServer interface {
	mustEmbedUnimplementedIdentityServiceServer()
}

func RegisterIdentityServiceServer(s grpc.ServiceRegistrar, srv IdentityServiceServer) {
	// If the following call panics, it indicates UnimplementedIdentityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityService_ServiceDesc, srv)
}

func _IdentityService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_VerifyOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).VerifyOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_VerifyOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).VerifyOTP(ctx, req.(*VerifyOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_ForgotPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgotPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).ForgotPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_ForgotPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).ForgotPassword(ctx, req.(*ForgotPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_CreateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).CreateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_CreateRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).CreateRole(ctx, req.(*CreateRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_AssignRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).AssignRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_AssignRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).AssignRole(ctx, req.(*AssignRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetRoles(ctx, req.(*GetRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_CreateBusinessUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBusinessUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).CreateBusinessUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_CreateBusinessUnit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).CreateBusinessUnit(ctx, req.(*CreateBusinessUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetBusinessUnits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBusinessUnitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetBusinessUnits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetBusinessUnits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetBusinessUnits(ctx, req.(*GetBusinessUnitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_UpdateBusinessUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBusinessUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).UpdateBusinessUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_UpdateBusinessUnit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).UpdateBusinessUnit(ctx, req.(*UpdateBusinessUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_DeleteBusinessUnit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBusinessUnitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).DeleteBusinessUnit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_DeleteBusinessUnit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).DeleteBusinessUnit(ctx, req.(*DeleteBusinessUnitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_SetPIN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPINRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).SetPIN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_SetPIN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).SetPIN(ctx, req.(*SetPINRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_VerifyPIN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPINRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).VerifyPIN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_VerifyPIN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).VerifyPIN(ctx, req.(*VerifyPINRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_CheckAccountStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).CheckAccountStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_CheckAccountStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).CheckAccountStatus(ctx, req.(*CheckStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_UpdateKYCLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateKYCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).UpdateKYCLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_UpdateKYCLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).UpdateKYCLevel(ctx, req.(*UpdateKYCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetKYCStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKYCStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetKYCStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetKYCStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetKYCStatus(ctx, req.(*GetKYCStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetSecurityQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetSecurityQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetSecurityQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetSecurityQuestions(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_SetUserSecurityQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserQuestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).SetUserSecurityQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_SetUserSecurityQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).SetUserSecurityQuestions(ctx, req.(*SetUserQuestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_VerifySecurityAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).VerifySecurityAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_VerifySecurityAnswer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).VerifySecurityAnswer(ctx, req.(*VerifyAnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_ExportData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).ExportData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_ExportData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).ExportData(ctx, req.(*ExportDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_DeleteAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).DeleteAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_DeleteAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).DeleteAccount(ctx, req.(*DeleteAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_UpdateConsent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConsentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).UpdateConsent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_UpdateConsent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).UpdateConsent(ctx, req.(*UpdateConsentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityService_ServiceDesc is the grpc.ServiceDesc for IdentityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "identity.IdentityService",
	HandlerType: (*IdentityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _IdentityService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _IdentityService_Login_Handler,
		},
		{
			MethodName: "VerifyOTP",
			Handler:    _IdentityService_VerifyOTP_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _IdentityService_GetProfile_Handler,
		},
		{
			MethodName: "ForgotPassword",
			Handler:    _IdentityService_ForgotPassword_Handler,
		},
		{
			MethodName: "CreateRole",
			Handler:    _IdentityService_CreateRole_Handler,
		},
		{
			MethodName: "AssignRole",
			Handler:    _IdentityService_AssignRole_Handler,
		},
		{
			MethodName: "GetRoles",
			Handler:    _IdentityService_GetRoles_Handler,
		},
		{
			MethodName: "CreateBusinessUnit",
			Handler:    _IdentityService_CreateBusinessUnit_Handler,
		},
		{
			MethodName: "GetBusinessUnits",
			Handler:    _IdentityService_GetBusinessUnits_Handler,
		},
		{
			MethodName: "UpdateBusinessUnit",
			Handler:    _IdentityService_UpdateBusinessUnit_Handler,
		},
		{
			MethodName: "DeleteBusinessUnit",
			Handler:    _IdentityService_DeleteBusinessUnit_Handler,
		},
		{
			MethodName: "SetPIN",
			Handler:    _IdentityService_SetPIN_Handler,
		},
		{
			MethodName: "VerifyPIN",
			Handler:    _IdentityService_VerifyPIN_Handler,
		},
		{
			MethodName: "CheckAccountStatus",
			Handler:    _IdentityService_CheckAccountStatus_Handler,
		},
		{
			MethodName: "UpdateKYCLevel",
			Handler:    _IdentityService_UpdateKYCLevel_Handler,
		},
		{
			MethodName: "GetKYCStatus",
			Handler:    _IdentityService_GetKYCStatus_Handler,
		},
		{
			MethodName: "GetSecurityQuestions",
			Handler:    _IdentityService_GetSecurityQuestions_Handler,
		},
		{
			MethodName: "SetUserSecurityQuestions",
			Handler:    _IdentityService_SetUserSecurityQuestions_Handler,
		},
		{
			MethodName: "VerifySecurityAnswer",
			Handler:    _IdentityService_VerifySecurityAnswer_Handler,
		},
		{
			MethodName: "ExportData",
			Handler:    _IdentityService_ExportData_Handler,
		},
		{
			MethodName: "DeleteAccount",
			Handler:    _IdentityService_DeleteAccount_Handler,
		},
		{
			MethodName: "UpdateConsent",
			Handler:    _IdentityService_UpdateConsent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
