// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: user.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

type UpdateKYCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetLevel   int32                  `protobuf:"varint,2,opt,name=target_level,json=targetLevel,proto3" json:"target_level,omitempty"` // 1, 2, 3
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKYCRequest) Reset() {
	*x = UpdateKYCRequest{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKYCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKYCRequest) ProtoMessage() {}

func (x *UpdateKYCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKYCRequest.ProtoReflect.Descriptor instead.
func (*UpdateKYCRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateKYCRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateKYCRequest) GetTargetLevel() int32 {
	if x != nil {
		return x.TargetLevel
	}
	return 0
}

type UpdateKYCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKYCResponse) Reset() {
	*x = UpdateKYCResponse{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKYCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKYCResponse) ProtoMessage() {}

func (x *UpdateKYCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKYCResponse.ProtoReflect.Descriptor instead.
func (*UpdateKYCResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateKYCResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateKYCResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetKYCStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKYCStatusRequest) Reset() {
	*x = GetKYCStatusRequest{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKYCStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKYCStatusRequest) ProtoMessage() {}

func (x *GetKYCStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKYCStatusRequest.ProtoReflect.Descriptor instead.
func (*GetKYCStatusRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetKYCStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetKYCStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentLevel  int32                  `protobuf:"varint,1,opt,name=current_level,json=currentLevel,proto3" json:"current_level,omitempty"`
	LevelName     string                 `protobuf:"bytes,2,opt,name=level_name,json=levelName,proto3" json:"level_name,omitempty"`
	DailyLimit    float64                `protobuf:"fixed64,3,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`
	MaxBalance    float64                `protobuf:"fixed64,4,opt,name=max_balance,json=maxBalance,proto3" json:"max_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKYCStatusResponse) Reset() {
	*x = GetKYCStatusResponse{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKYCStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKYCStatusResponse) ProtoMessage() {}

func (x *GetKYCStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKYCStatusResponse.ProtoReflect.Descriptor instead.
func (*GetKYCStatusResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetKYCStatusResponse) GetCurrentLevel() int32 {
	if x != nil {
		return x.CurrentLevel
	}
	return 0
}

func (x *GetKYCStatusResponse) GetLevelName() string {
	if x != nil {
		return x.LevelName
	}
	return ""
}

func (x *GetKYCStatusResponse) GetDailyLimit() float64 {
	if x != nil {
		return x.DailyLimit
	}
	return 0
}

func (x *GetKYCStatusResponse) GetMaxBalance() float64 {
	if x != nil {
		return x.MaxBalance
	}
	return 0
}

type SecurityQuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*QuestionInfo        `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityQuestionsResponse) Reset() {
	*x = SecurityQuestionsResponse{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityQuestionsResponse) ProtoMessage() {}

func (x *SecurityQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityQuestionsResponse.ProtoReflect.Descriptor instead.
func (*SecurityQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *SecurityQuestionsResponse) GetQuestions() []*QuestionInfo {
	if x != nil {
		return x.Questions
	}
	return nil
}

type QuestionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionInfo) Reset() {
	*x = QuestionInfo{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionInfo) ProtoMessage() {}

func (x *QuestionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionInfo.ProtoReflect.Descriptor instead.
func (*QuestionInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *QuestionInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QuestionInfo) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type SetUserQuestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Answers       []*UserQuestionAnswer  `protobuf:"bytes,2,rep,name=answers,proto3" json:"answers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserQuestionsRequest) Reset() {
	*x = SetUserQuestionsRequest{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserQuestionsRequest) ProtoMessage() {}

func (x *SetUserQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserQuestionsRequest.ProtoReflect.Descriptor instead.
func (*SetUserQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *SetUserQuestionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetUserQuestionsRequest) GetAnswers() []*UserQuestionAnswer {
	if x != nil {
		return x.Answers
	}
	return nil
}

type UserQuestionAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    uint32                 `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Answer        string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserQuestionAnswer) Reset() {
	*x = UserQuestionAnswer{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserQuestionAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserQuestionAnswer) ProtoMessage() {}

func (x *UserQuestionAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserQuestionAnswer.ProtoReflect.Descriptor instead.
func (*UserQuestionAnswer) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *UserQuestionAnswer) GetQuestionId() uint32 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *UserQuestionAnswer) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type SetUserQuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserQuestionsResponse) Reset() {
	*x = SetUserQuestionsResponse{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserQuestionsResponse) ProtoMessage() {}

func (x *SetUserQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserQuestionsResponse.ProtoReflect.Descriptor instead.
func (*SetUserQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *SetUserQuestionsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type VerifyAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuestionId    uint32                 `protobuf:"varint,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Answer        string                 `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAnswerRequest) Reset() {
	*x = VerifyAnswerRequest{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAnswerRequest) ProtoMessage() {}

func (x *VerifyAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAnswerRequest.ProtoReflect.Descriptor instead.
func (*VerifyAnswerRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *VerifyAnswerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyAnswerRequest) GetQuestionId() uint32 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *VerifyAnswerRequest) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type VerifyAnswerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAnswerResponse) Reset() {
	*x = VerifyAnswerResponse{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAnswerResponse) ProtoMessage() {}

func (x *VerifyAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAnswerResponse.ProtoReflect.Descriptor instead.
func (*VerifyAnswerResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *VerifyAnswerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SetPINRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pin           string                 `protobuf:"bytes,2,opt,name=pin,proto3" json:"pin,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // LOGIN or TRANSACTION
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPINRequest) Reset() {
	*x = SetPINRequest{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPINRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPINRequest) ProtoMessage() {}

func (x *SetPINRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPINRequest.ProtoReflect.Descriptor instead.
func (*SetPINRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *SetPINRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetPINRequest) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

func (x *SetPINRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type SetPINResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPINResponse) Reset() {
	*x = SetPINResponse{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPINResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPINResponse) ProtoMessage() {}

func (x *SetPINResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPINResponse.ProtoReflect.Descriptor instead.
func (*SetPINResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *SetPINResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetPINResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VerifyPINRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pin           string                 `protobuf:"bytes,2,opt,name=pin,proto3" json:"pin,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // LOGIN or TRANSACTION
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPINRequest) Reset() {
	*x = VerifyPINRequest{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPINRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPINRequest) ProtoMessage() {}

func (x *VerifyPINRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPINRequest.ProtoReflect.Descriptor instead.
func (*VerifyPINRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *VerifyPINRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyPINRequest) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

func (x *VerifyPINRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type VerifyPINResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPINResponse) Reset() {
	*x = VerifyPINResponse{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPINResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPINResponse) ProtoMessage() {}

func (x *VerifyPINResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPINResponse.ProtoReflect.Descriptor instead.
func (*VerifyPINResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *VerifyPINResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CheckStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStatusRequest) Reset() {
	*x = CheckStatusRequest{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStatusRequest) ProtoMessage() {}

func (x *CheckStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStatusRequest.ProtoReflect.Descriptor instead.
func (*CheckStatusRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *CheckStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CheckStatusResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Status              string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	IsPinSet            bool                   `protobuf:"varint,2,opt,name=is_pin_set,json=isPinSet,proto3" json:"is_pin_set,omitempty"`
	IsTransactionPinSet bool                   `protobuf:"varint,3,opt,name=is_transaction_pin_set,json=isTransactionPinSet,proto3" json:"is_transaction_pin_set,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CheckStatusResponse) Reset() {
	*x = CheckStatusResponse{}
	mi := &file_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStatusResponse) ProtoMessage() {}

func (x *CheckStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStatusResponse.ProtoReflect.Descriptor instead.
func (*CheckStatusResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

func (x *CheckStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CheckStatusResponse) GetIsPinSet() bool {
	if x != nil {
		return x.IsPinSet
	}
	return false
}

func (x *CheckStatusResponse) GetIsTransactionPinSet() bool {
	if x != nil {
		return x.IsTransactionPinSet
	}
	return false
}

type CreateBusinessUnitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ManagerId     string                 `protobuf:"bytes,2,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBusinessUnitRequest) Reset() {
	*x = CreateBusinessUnitRequest{}
	mi := &file_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBusinessUnitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBusinessUnitRequest) ProtoMessage() {}

func (x *CreateBusinessUnitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBusinessUnitRequest.ProtoReflect.Descriptor instead.
func (*CreateBusinessUnitRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{18}
}

func (x *CreateBusinessUnitRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBusinessUnitRequest) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

type CreateBusinessUnitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UnitId        string                 `protobuf:"bytes,2,opt,name=unit_id,json=unitId,proto3" json:"unit_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBusinessUnitResponse) Reset() {
	*x = CreateBusinessUnitResponse{}
	mi := &file_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBusinessUnitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBusinessUnitResponse) ProtoMessage() {}

func (x *CreateBusinessUnitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBusinessUnitResponse.ProtoReflect.Descriptor instead.
func (*CreateBusinessUnitResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{19}
}

func (x *CreateBusinessUnitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateBusinessUnitResponse) GetUnitId() string {
	if x != nil {
		return x.UnitId
	}
	return ""
}

type GetBusinessUnitsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBusinessUnitsRequest) Reset() {
	*x = GetBusinessUnitsRequest{}
	mi := &file_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBusinessUnitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBusinessUnitsRequest) ProtoMessage() {}

func (x *GetBusinessUnitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBusinessUnitsRequest.ProtoReflect.Descriptor instead.
func (*GetBusinessUnitsRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{20}
}

type GetBusinessUnitsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Units         []*BusinessUnitInfo    `protobuf:"bytes,1,rep,name=units,proto3" json:"units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBusinessUnitsResponse) Reset() {
	*x = GetBusinessUnitsResponse{}
	mi := &file_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBusinessUnitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBusinessUnitsResponse) ProtoMessage() {}

func (x *GetBusinessUnitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBusinessUnitsResponse.ProtoReflect.Descriptor instead.
func (*GetBusinessUnitsResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{21}
}

func (x *GetBusinessUnitsResponse) GetUnits() []*BusinessUnitInfo {
	if x != nil {
		return x.Units
	}
	return nil
}

type UpdateBusinessUnitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ManagerId     string                 `protobuf:"bytes,3,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBusinessUnitRequest) Reset() {
	*x = UpdateBusinessUnitRequest{}
	mi := &file_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBusinessUnitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBusinessUnitRequest) ProtoMessage() {}

func (x *UpdateBusinessUnitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBusinessUnitRequest.ProtoReflect.Descriptor instead.
func (*UpdateBusinessUnitRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateBusinessUnitRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBusinessUnitRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateBusinessUnitRequest) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

type UpdateBusinessUnitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBusinessUnitResponse) Reset() {
	*x = UpdateBusinessUnitResponse{}
	mi := &file_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBusinessUnitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBusinessUnitResponse) ProtoMessage() {}

func (x *UpdateBusinessUnitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBusinessUnitResponse.ProtoReflect.Descriptor instead.
func (*UpdateBusinessUnitResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateBusinessUnitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateBusinessUnitResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteBusinessUnitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBusinessUnitRequest) Reset() {
	*x = DeleteBusinessUnitRequest{}
	mi := &file_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBusinessUnitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBusinessUnitRequest) ProtoMessage() {}

func (x *DeleteBusinessUnitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBusinessUnitRequest.ProtoReflect.Descriptor instead.
func (*DeleteBusinessUnitRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteBusinessUnitRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBusinessUnitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBusinessUnitResponse) Reset() {
	*x = DeleteBusinessUnitResponse{}
	mi := &file_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBusinessUnitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBusinessUnitResponse) ProtoMessage() {}

func (x *DeleteBusinessUnitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBusinessUnitResponse.ProtoReflect.Descriptor instead.
func (*DeleteBusinessUnitResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteBusinessUnitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteBusinessUnitResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BusinessUnitInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ManagerId     string                 `protobuf:"bytes,3,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusinessUnitInfo) Reset() {
	*x = BusinessUnitInfo{}
	mi := &file_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessUnitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessUnitInfo) ProtoMessage() {}

func (x *BusinessUnitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessUnitInfo.ProtoReflect.Descriptor instead.
func (*BusinessUnitInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{26}
}

func (x *BusinessUnitInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BusinessUnitInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BusinessUnitInfo) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Permissions   []string               `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{27}
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type CreateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RoleId        string                 `protobuf:"bytes,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleResponse) Reset() {
	*x = CreateRoleResponse{}
	mi := &file_user_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleResponse) ProtoMessage() {}

func (x *CreateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleResponse.ProtoReflect.Descriptor instead.
func (*CreateRoleResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{28}
}

func (x *CreateRoleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateRoleResponse) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

type AssignRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleName      string                 `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleRequest) Reset() {
	*x = AssignRoleRequest{}
	mi := &file_user_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleRequest) ProtoMessage() {}

func (x *AssignRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleRequest.ProtoReflect.Descriptor instead.
func (*AssignRoleRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{29}
}

func (x *AssignRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssignRoleRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

type AssignRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleResponse) Reset() {
	*x = AssignRoleResponse{}
	mi := &file_user_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleResponse) ProtoMessage() {}

func (x *AssignRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleResponse.ProtoReflect.Descriptor instead.
func (*AssignRoleResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{30}
}

func (x *AssignRoleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolesRequest) Reset() {
	*x = GetRolesRequest{}
	mi := &file_user_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolesRequest) ProtoMessage() {}

func (x *GetRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolesRequest.ProtoReflect.Descriptor instead.
func (*GetRolesRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{31}
}

type GetRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*RoleInfo            `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolesResponse) Reset() {
	*x = GetRolesResponse{}
	mi := &file_user_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolesResponse) ProtoMessage() {}

func (x *GetRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolesResponse.ProtoReflect.Descriptor instead.
func (*GetRolesResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{32}
}

func (x *GetRolesResponse) GetRoles() []*RoleInfo {
	if x != nil {
		return x.Roles
	}
	return nil
}

type RoleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Permissions   []string               `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleInfo) Reset() {
	*x = RoleInfo{}
	mi := &file_user_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfo) ProtoMessage() {}

func (x *RoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfo.ProtoReflect.Descriptor instead.
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{33}
}

func (x *RoleInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleInfo) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type RegisterRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Email                 string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password              string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FirstName             string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName              string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	PhoneNumber           string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Bvn                   string                 `protobuf:"bytes,6,opt,name=bvn,proto3" json:"bvn,omitempty"`
	TermsAccepted         bool                   `protobuf:"varint,7,opt,name=terms_accepted,json=termsAccepted,proto3" json:"terms_accepted,omitempty"`
	PrivacyPolicyAccepted bool                   `protobuf:"varint,8,opt,name=privacy_policy_accepted,json=privacyPolicyAccepted,proto3" json:"privacy_policy_accepted,omitempty"`
	MarketingConsent      bool                   `protobuf:"varint,9,opt,name=marketing_consent,json=marketingConsent,proto3" json:"marketing_consent,omitempty"`
	PolicyVersion         string                 `protobuf:"bytes,10,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_user_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{34}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegisterRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *RegisterRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *RegisterRequest) GetBvn() string {
	if x != nil {
		return x.Bvn
	}
	return ""
}

func (x *RegisterRequest) GetTermsAccepted() bool {
	if x != nil {
		return x.TermsAccepted
	}
	return false
}

func (x *RegisterRequest) GetPrivacyPolicyAccepted() bool {
	if x != nil {
		return x.PrivacyPolicyAccepted
	}
	return false
}

func (x *RegisterRequest) GetMarketingConsent() bool {
	if x != nil {
		return x.MarketingConsent
	}
	return false
}

func (x *RegisterRequest) GetPolicyVersion() string {
	if x != nil {
		return x.PolicyVersion
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_user_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{35}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_user_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{36}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *LoginRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Requires_2Fa  bool                   `protobuf:"varint,4,opt,name=requires_2fa,json=requires2fa,proto3" json:"requires_2fa,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	UserId        string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_user_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{37}
}

func (x *LoginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetRequires_2Fa() bool {
	if x != nil {
		return x.Requires_2Fa
	}
	return false
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type VerifyOTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyOTPRequest) Reset() {
	*x = VerifyOTPRequest{}
	mi := &file_user_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOTPRequest) ProtoMessage() {}

func (x *VerifyOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOTPRequest.ProtoReflect.Descriptor instead.
func (*VerifyOTPRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{38}
}

func (x *VerifyOTPRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerifyOTPRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *VerifyOTPRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type VerifyOTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyOTPResponse) Reset() {
	*x = VerifyOTPResponse{}
	mi := &file_user_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOTPResponse) ProtoMessage() {}

func (x *VerifyOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOTPResponse.ProtoReflect.Descriptor instead.
func (*VerifyOTPResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{39}
}

func (x *VerifyOTPResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VerifyOTPResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_user_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{40}
}

func (x *GetProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	UserType      string                 `protobuf:"bytes,6,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`
	Role          *RoleInfo              `protobuf:"bytes,7,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_user_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{41}
}

func (x *GetProfileResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetProfileResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *GetProfileResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *GetProfileResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *GetProfileResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetProfileResponse) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

func (x *GetProfileResponse) GetRole() *RoleInfo {
	if x != nil {
		return x.Role
	}
	return nil
}

type ForgotPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgotPasswordRequest) Reset() {
	*x = ForgotPasswordRequest{}
	mi := &file_user_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordRequest) ProtoMessage() {}

func (x *ForgotPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordRequest.ProtoReflect.Descriptor instead.
func (*ForgotPasswordRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{42}
}

func (x *ForgotPasswordRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ForgotPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgotPasswordResponse) Reset() {
	*x = ForgotPasswordResponse{}
	mi := &file_user_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgotPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPasswordResponse) ProtoMessage() {}

func (x *ForgotPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPasswordResponse.ProtoReflect.Descriptor instead.
func (*ForgotPasswordResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{43}
}

func (x *ForgotPasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ForgotPasswordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ExportDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportDataRequest) Reset() {
	*x = ExportDataRequest{}
	mi := &file_user_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportDataRequest) ProtoMessage() {}

func (x *ExportDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportDataRequest.ProtoReflect.Descriptor instead.
func (*ExportDataRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{44}
}

func (x *ExportDataRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ExportDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonData      string                 `protobuf:"bytes,1,opt,name=json_data,json=jsonData,proto3" json:"json_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportDataResponse) Reset() {
	*x = ExportDataResponse{}
	mi := &file_user_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportDataResponse) ProtoMessage() {}

func (x *ExportDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportDataResponse.ProtoReflect.Descriptor instead.
func (*ExportDataResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{45}
}

func (x *ExportDataResponse) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

type DeleteAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountRequest) Reset() {
	*x = DeleteAccountRequest{}
	mi := &file_user_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountRequest) ProtoMessage() {}

func (x *DeleteAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{46}
}

func (x *DeleteAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountResponse) Reset() {
	*x = DeleteAccountResponse{}
	mi := &file_user_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountResponse) ProtoMessage() {}

func (x *DeleteAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{47}
}

func (x *DeleteAccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteAccountResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateConsentRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	UserId                string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TermsAccepted         bool                   `protobuf:"varint,2,opt,name=terms_accepted,json=termsAccepted,proto3" json:"terms_accepted,omitempty"`
	PrivacyPolicyAccepted bool                   `protobuf:"varint,3,opt,name=privacy_policy_accepted,json=privacyPolicyAccepted,proto3" json:"privacy_policy_accepted,omitempty"`
	MarketingConsent      bool                   `protobuf:"varint,4,opt,name=marketing_consent,json=marketingConsent,proto3" json:"marketing_consent,omitempty"`
	PolicyVersion         string                 `protobuf:"bytes,5,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateConsentRequest) Reset() {
	*x = UpdateConsentRequest{}
	mi := &file_user_proto_msgTypes[48]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConsentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConsentRequest) ProtoMessage() {}

func (x *UpdateConsentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[48]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConsentRequest.ProtoReflect.Descriptor instead.
func (*UpdateConsentRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{48}
}

func (x *UpdateConsentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateConsentRequest) GetTermsAccepted() bool {
	if x != nil {
		return x.TermsAccepted
	}
	return false
}

func (x *UpdateConsentRequest) GetPrivacyPolicyAccepted() bool {
	if x != nil {
		return x.PrivacyPolicyAccepted
	}
	return false
}

func (x *UpdateConsentRequest) GetMarketingConsent() bool {
	if x != nil {
		return x.MarketingConsent
	}
	return false
}

func (x *UpdateConsentRequest) GetPolicyVersion() string {
	if x != nil {
		return x.PolicyVersion
	}
	return ""
}

type UpdateConsentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConsentResponse) Reset() {
	*x = UpdateConsentResponse{}
	mi := &file_user_proto_msgTypes[49]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConsentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConsentResponse) ProtoMessage() {}

func (x *UpdateConsentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[49]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConsentResponse.ProtoReflect.Descriptor instead.
func (*UpdateConsentResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{49}
}

func (x *UpdateConsentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateConsentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\bidentity\"\a\n" +
	"\x05Empty\"N\n" +
	"\x10UpdateKYCRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\ftarget_level\x18\x02 \x01(\x05R\vtargetLevel\"G\n" +
	"\x11UpdateKYCResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\".\n" +
	"\x13GetKYCStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x9c\x01\n" +
	"\x14GetKYCStatusResponse\x12#\n" +
	"\rcurrent_level\x18\x01 \x01(\x05R\fcurrentLevel\x12\x1d\n" +
	"\n" +
	"level_name\x18\x02 \x01(\tR\tlevelName\x12\x1f\n" +
	"\vdaily_limit\x18\x03 \x01(\x01R\n" +
	"dailyLimit\x12\x1f\n" +
	"\vmax_balance\x18\x04 \x01(\x01R\n" +
	"maxBalance\"Q\n" +
	"\x19SecurityQuestionsResponse\x124\n" +
	"\tquestions\x18\x01 \x03(\v2\x16.identity.QuestionInfoR\tquestions\":\n" +
	"\fQuestionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\"j\n" +
	"\x17SetUserQuestionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x126\n" +
	"\aanswers\x18\x02 \x03(\v2\x1c.identity.UserQuestionAnswerR\aanswers\"M\n" +
	"\x12UserQuestionAnswer\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\rR\n" +
	"questionId\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer\"4\n" +
	"\x18SetUserQuestionsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"g\n" +
	"\x13VerifyAnswerRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\rR\n" +
	"questionId\x12\x16\n" +
	"\x06answer\x18\x03 \x01(\tR\x06answer\"0\n" +
	"\x14VerifyAnswerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"N\n" +
	"\rSetPINRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x10\n" +
	"\x03pin\x18\x02 \x01(\tR\x03pin\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"D\n" +
	"\x0eSetPINResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"Q\n" +
	"\x10VerifyPINRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x10\n" +
	"\x03pin\x18\x02 \x01(\tR\x03pin\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"-\n" +
	"\x11VerifyPINResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"-\n" +
	"\x12CheckStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x80\x01\n" +
	"\x13CheckStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1c\n" +
	"\n" +
	"is_pin_set\x18\x02 \x01(\bR\bisPinSet\x123\n" +
	"\x16is_transaction_pin_set\x18\x03 \x01(\bR\x13isTransactionPinSet\"N\n" +
	"\x19CreateBusinessUnitRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x02 \x01(\tR\tmanagerId\"O\n" +
	"\x1aCreateBusinessUnitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\aunit_id\x18\x02 \x01(\tR\x06unitId\"\x19\n" +
	"\x17GetBusinessUnitsRequest\"L\n" +
	"\x18GetBusinessUnitsResponse\x120\n" +
	"\x05units\x18\x01 \x03(\v2\x1a.identity.BusinessUnitInfoR\x05units\"^\n" +
	"\x19UpdateBusinessUnitRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x03 \x01(\tR\tmanagerId\"P\n" +
	"\x1aUpdateBusinessUnitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"+\n" +
	"\x19DeleteBusinessUnitRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"P\n" +
	"\x1aDeleteBusinessUnitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"U\n" +
	"\x10BusinessUnitInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x03 \x01(\tR\tmanagerId\"I\n" +
	"\x11CreateRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions\"G\n" +
	"\x12CreateRoleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\tR\x06roleId\"I\n" +
	"\x11AssignRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\trole_name\x18\x02 \x01(\tR\broleName\".\n" +
	"\x12AssignRoleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x11\n" +
	"\x0fGetRolesRequest\"<\n" +
	"\x10GetRolesResponse\x12(\n" +
	"\x05roles\x18\x01 \x03(\v2\x12.identity.RoleInfoR\x05roles\"P\n" +
	"\bRoleInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vpermissions\x18\x03 \x03(\tR\vpermissions\"\xe7\x02\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12\x10\n" +
	"\x03bvn\x18\x06 \x01(\tR\x03bvn\x12%\n" +
	"\x0eterms_accepted\x18\a \x01(\bR\rtermsAccepted\x126\n" +
	"\x17privacy_policy_accepted\x18\b \x01(\bR\x15privacyPolicyAccepted\x12+\n" +
	"\x11marketing_consent\x18\t \x01(\bR\x10marketingConsent\x12%\n" +
	"\x0epolicy_version\x18\n" +
	" \x01(\tR\rpolicyVersion\"_\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"~\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\"\xa1\x01\n" +
	"\rLoginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12!\n" +
	"\frequires_2fa\x18\x04 \x01(\bR\vrequires2fa\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"P\n" +
	"\x10VerifyOTPRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"G\n" +
	"\x11VerifyOTPResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xa1\x01\n" +
	"\x12GetProfileResponse\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"-\n" +
	"\x15ForgotPasswordRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"L\n" +
	"\x16ForgotPasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x11ExportDataRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"1\n" +
	"\x12ExportDataResponse\x12\x1b\n" +
	"\tjson_data\x18\x01 \x01(\tR\bjsonData\"/\n" +
	"\x14DeleteAccountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"K\n" +
	"\x15DeleteAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe2\x01\n" +
	"\x14UpdateConsentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0eterms_accepted\x18\x02 \x01(\bR\rtermsAccepted\x126\n" +
	"\x17privacy_policy_accepted\x18\x03 \x01(\bR\x15privacyPolicyAccepted\x12+\n" +
	"\x11marketing_consent\x18\x04 \x01(\bR\x10marketingConsent\x12%\n" +
	"\x0epolicy_version\x18\x05 \x01(\tR\rpolicyVersion\"K\n" +
	"\x15UpdateConsentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xd8\x0e\n" +
	"\x0fIdentityService\x12C\n" +
	"\bRegister\x12\x19.identity.RegisterRequest\x1a\x1a.identity.RegisterResponse\"\x00\x12:\n" +
	"\x05Login\x12\x16.identity.LoginRequest\x1a\x17.identity.LoginResponse\"\x00\x12F\n" +
	"\tVerifyOTP\x12\x1a.identity.VerifyOTPRequest\x1a\x1b.identity.VerifyOTPResponse\"\x00\x12I\n" +
	"\n" +
	"GetProfile\x12\x1b.identity.GetProfileRequest\x1a\x1c.identity.GetProfileResponse\"\x00\x12U\n" +
	"\x0eForgotPassword\x12\x1f.identity.ForgotPasswordRequest\x1a .identity.ForgotPasswordResponse\"\x00\x12I\n" +
	"\n" +
	"CreateRole\x12\x1b.identity.CreateRoleRequest\x1a\x1c.identity.CreateRoleResponse\"\x00\x12I\n" +
	"\n" +
	"AssignRole\x12\x1b.identity.AssignRoleRequest\x1a\x1c.identity.AssignRoleResponse\"\x00\x12C\n" +
	"\bGetRoles\x12\x19.identity.GetRolesRequest\x1a\x1a.identity.GetRolesResponse\"\x00\x12a\n" +
	"\x12CreateBusinessUnit\x12#.identity.CreateBusinessUnitRequest\x1a$.identity.CreateBusinessUnitResponse\"\x00\x12[\n" +
	"\x10GetBusinessUnits\x12!.identity.GetBusinessUnitsRequest\x1a\".identity.GetBusinessUnitsResponse\"\x00\x12a\n" +
	"\x12UpdateBusinessUnit\x12#.identity.UpdateBusinessUnitRequest\x1a$.identity.UpdateBusinessUnitResponse\"\x00\x12a\n" +
	"\x12DeleteBusinessUnit\x12#.identity.DeleteBusinessUnitRequest\x1a$.identity.DeleteBusinessUnitResponse\"\x00\x12=\n" +
	"\x06SetPIN\x12\x17.identity.SetPINRequest\x1a\x18.identity.SetPINResponse\"\x00\x12F\n" +
	"\tVerifyPIN\x12\x1a.identity.VerifyPINRequest\x1a\x1b.identity.VerifyPINResponse\"\x00\x12S\n" +
	"\x12CheckAccountStatus\x12\x1c.identity.CheckStatusRequest\x1a\x1d.identity.CheckStatusResponse\"\x00\x12K\n" +
	"\x0eUpdateKYCLevel\x12\x1a.identity.UpdateKYCRequest\x1a\x1b.identity.UpdateKYCResponse\"\x00\x12O\n" +
	"\fGetKYCStatus\x12\x1d.identity.GetKYCStatusRequest\x1a\x1e.identity.GetKYCStatusResponse\"\x00\x12N\n" +
	"\x14GetSecurityQuestions\x12\x0f.identity.Empty\x1a#.identity.SecurityQuestionsResponse\"\x00\x12c\n" +
	"\x18SetUserSecurityQuestions\x12!.identity.SetUserQuestionsRequest\x1a\".identity.SetUserQuestionsResponse\"\x00\x12W\n" +
	"\x14VerifySecurityAnswer\x12\x1d.identity.VerifyAnswerRequest\x1a\x1e.identity.VerifyAnswerResponse\"\x00\x12I\n" +
	"\n" +
	"ExportData\x12\x1b.identity.ExportDataRequest\x1a\x1c.identity.ExportDataResponse\"\x00\x12R\n" +
	"\rDeleteAccount\x12\x1e.identity.DeleteAccountRequest\x1a\x1f.identity.DeleteAccountResponse\"\x00\x12R\n" +
	"\rUpdateConsent\x12\x1e.identity.UpdateConsentRequest\x1a\x1f.identity.UpdateConsentResponse\"\x00B'Z%github.com/gdl/identity-service/protob\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 50)
var file_user_proto_goTypes = []any{
	(*Empty)(nil),                      // 0: identity.Empty
	(*UpdateKYCRequest)(nil),           // 1: identity.UpdateKYCRequest
	(*UpdateKYCResponse)(nil),          // 2: identity.UpdateKYCResponse
	(*GetKYCStatusRequest)(nil),        // 3: identity.GetKYCStatusRequest
	(*GetKYCStatusResponse)(nil),       // 4: identity.GetKYCStatusResponse
	(*SecurityQuestionsResponse)(nil),  // 5: identity.SecurityQuestionsResponse
	(*QuestionInfo)(nil),               // 6: identity.QuestionInfo
	(*SetUserQuestionsRequest)(nil),    // 7: identity.SetUserQuestionsRequest
	(*UserQuestionAnswer)(nil),         // 8: identity.UserQuestionAnswer
	(*SetUserQuestionsResponse)(nil),   // 9: identity.SetUserQuestionsResponse
	(*VerifyAnswerRequest)(nil),        // 10: identity.VerifyAnswerRequest
	(*VerifyAnswerResponse)(nil),       // 11: identity.VerifyAnswerResponse
	(*SetPINRequest)(nil),              // 12: identity.SetPINRequest
	(*SetPINResponse)(nil),             // 13: identity.SetPINResponse
	(*VerifyPINRequest)(nil),           // 14: identity.VerifyPINRequest
	(*VerifyPINResponse)(nil),          // 15: identity.VerifyPINResponse
	(*CheckStatusRequest)(nil),         // 16: identity.CheckStatusRequest
	(*CheckStatusResponse)(nil),        // 17: identity.CheckStatusResponse
	(*CreateBusinessUnitRequest)(nil),  // 18: identity.CreateBusinessUnitRequest
	(*CreateBusinessUnitResponse)(nil), // 19: identity.CreateBusinessUnitResponse
	(*GetBusinessUnitsRequest)(nil),    // 20: identity.GetBusinessUnitsRequest
	(*GetBusinessUnitsResponse)(nil),   // 21: identity.GetBusinessUnitsResponse
	(*UpdateBusinessUnitRequest)(nil),  // 22: identity.UpdateBusinessUnitRequest
	(*UpdateBusinessUnitResponse)(nil), // 23: identity.UpdateBusinessUnitResponse
	(*DeleteBusinessUnitRequest)(nil),  // 24: identity.DeleteBusinessUnitRequest
	(*DeleteBusinessUnitResponse)(nil), // 25: identity.DeleteBusinessUnitResponse
	(*BusinessUnitInfo)(nil),           // 26: identity.BusinessUnitInfo
	(*CreateRoleRequest)(nil),          // 27: identity.CreateRoleRequest
	(*CreateRoleResponse)(nil),         // 28: identity.CreateRoleResponse
	(*AssignRoleRequest)(nil),          // 29: identity.AssignRoleRequest
	(*AssignRoleResponse)(nil),         // 30: identity.AssignRoleResponse
	(*GetRolesRequest)(nil),            // 31: identity.GetRolesRequest
	(*GetRolesResponse)(nil),           // 32: identity.GetRolesResponse
	(*RoleInfo)(nil),                   // 33: identity.RoleInfo
	(*RegisterRequest)(nil),            // 34: identity.RegisterRequest
	(*RegisterResponse)(nil),           // 35: identity.RegisterResponse
	(*LoginRequest)(nil),               // 36: identity.LoginRequest
	(*LoginResponse)(nil),              // 37: identity.LoginResponse
	(*VerifyOTPRequest)(nil),           // 38: identity.VerifyOTPRequest
	(*VerifyOTPResponse)(nil),          // 39: identity.VerifyOTPResponse
	(*GetProfileRequest)(nil),          // 40: identity.GetProfileRequest
	(*GetProfileResponse)(nil),         // 41: identity.GetProfileResponse
	(*ForgotPasswordRequest)(nil),      // 42: identity.ForgotPasswordRequest
	(*ForgotPasswordResponse)(nil),     // 43: identity.ForgotPasswordResponse
	(*ExportDataRequest)(nil),          // 44: identity.ExportDataRequest
	(*ExportDataResponse)(nil),         // 45: identity.ExportDataResponse
	(*DeleteAccountRequest)(nil),       // 46: identity.DeleteAccountRequest
	(*DeleteAccountResponse)(nil),      // 47: identity.DeleteAccountResponse
	(*UpdateConsentRequest)(nil),       // 48: identity.UpdateConsentRequest
	(*UpdateConsentResponse)(nil),      // 49: identity.UpdateConsentResponse
}
var file_user_proto_depIdxs = []int32{
	6,  // 0: identity.SecurityQuestionsResponse.questions:type_name -> identity.QuestionInfo
	8,  // 1: identity.SetUserQuestionsRequest.answers:type_name -> identity.UserQuestionAnswer
	26, // 2: identity.GetBusinessUnitsResponse.units:type_name -> identity.BusinessUnitInfo
	33, // 3: identity.GetRolesResponse.roles:type_name -> identity.RoleInfo
	34, // 4: identity.IdentityService.Register:input_type -> identity.RegisterRequest
	36, // 5: identity.IdentityService.Login:input_type -> identity.LoginRequest
	38, // 6: identity.IdentityService.VerifyOTP:input_type -> identity.VerifyOTPRequest
	40, // 7: identity.IdentityService.GetProfile:input_type -> identity.GetProfileRequest
	42, // 8: identity.IdentityService.ForgotPassword:input_type -> identity.ForgotPasswordRequest
	27, // 9: identity.IdentityService.CreateRole:input_type -> identity.CreateRoleRequest
	29, // 10: identity.IdentityService.AssignRole:input_type -> identity.AssignRoleRequest
	31, // 11: identity.IdentityService.GetRoles:input_type -> identity.GetRolesRequest
	18, // 12: identity.IdentityService.CreateBusinessUnit:input_type -> identity.CreateBusinessUnitRequest
	20, // 13: identity.IdentityService.GetBusinessUnits:input_type -> identity.GetBusinessUnitsRequest
	22, // 14: identity.IdentityService.UpdateBusinessUnit:input_type -> identity.UpdateBusinessUnitRequest
	24, // 15: identity.IdentityService.DeleteBusinessUnit:input_type -> identity.DeleteBusinessUnitRequest
	12, // 16: identity.IdentityService.SetPIN:input_type -> identity.SetPINRequest
	14, // 17: identity.IdentityService.VerifyPIN:input_type -> identity.VerifyPINRequest
	16, // 18: identity.IdentityService.CheckAccountStatus:input_type -> identity.CheckStatusRequest
	1,  // 19: identity.IdentityService.UpdateKYCLevel:input_type -> identity.UpdateKYCRequest
	3,  // 20: identity.IdentityService.GetKYCStatus:input_type -> identity.GetKYCStatusRequest
	0,  // 21: identity.IdentityService.GetSecurityQuestions:input_type -> identity.Empty
	7,  // 22: identity.IdentityService.SetUserSecurityQuestions:input_type -> identity.SetUserQuestionsRequest
	10, // 23: identity.IdentityService.VerifySecurityAnswer:input_type -> identity.VerifyAnswerRequest
	44, // 24: identity.IdentityService.ExportData:input_type -> identity.ExportDataRequest
	46, // 25: identity.IdentityService.DeleteAccount:input_type -> identity.DeleteAccountRequest
	48, // 26: identity.IdentityService.UpdateConsent:input_type -> identity.UpdateConsentRequest
	35, // 27: identity.IdentityService.Register:output_type -> identity.RegisterResponse
	37, // 28: identity.IdentityService.Login:output_type -> identity.LoginResponse
	39, // 29: identity.IdentityService.VerifyOTP:output_type -> identity.VerifyOTPResponse
	41, // 30: identity.IdentityService.GetProfile:output_type -> identity.GetProfileResponse
	43, // 31: identity.IdentityService.ForgotPassword:output_type -> identity.ForgotPasswordResponse
	28, // 32: identity.IdentityService.CreateRole:output_type -> identity.CreateRoleResponse
	30, // 33: identity.IdentityService.AssignRole:output_type -> identity.AssignRoleResponse
	32, // 34: identity.IdentityService.GetRoles:output_type -> identity.GetRolesResponse
	19, // 35: identity.IdentityService.CreateBusinessUnit:output_type -> identity.CreateBusinessUnitResponse
	21, // 36: identity.IdentityService.GetBusinessUnits:output_type -> identity.GetBusinessUnitsResponse
	23, // 37: identity.IdentityService.UpdateBusinessUnit:output_type -> identity.UpdateBusinessUnitResponse
	25, // 38: identity.IdentityService.DeleteBusinessUnit:output_type -> identity.DeleteBusinessUnitResponse
	13, // 39: identity.IdentityService.SetPIN:output_type -> identity.SetPINResponse
	15, // 40: identity.IdentityService.VerifyPIN:output_type -> identity.VerifyPINResponse
	17, // 41: identity.IdentityService.CheckAccountStatus:output_type -> identity.CheckStatusResponse
	2,  // 42: identity.IdentityService.UpdateKYCLevel:output_type -> identity.UpdateKYCResponse
	4,  // 43: identity.IdentityService.GetKYCStatus:output_type -> identity.GetKYCStatusResponse
	5,  // 44: identity.IdentityService.GetSecurityQuestions:output_type -> identity.SecurityQuestionsResponse
	9,  // 45: identity.IdentityService.SetUserSecurityQuestions:output_type -> identity.SetUserQuestionsResponse
	11, // 46: identity.IdentityService.VerifySecurityAnswer:output_type -> identity.VerifyAnswerResponse
	45, // 47: identity.IdentityService.ExportData:output_type -> identity.ExportDataResponse
	47, // 48: identity.IdentityService.DeleteAccount:output_type -> identity.DeleteAccountResponse
	49, // 49: identity.IdentityService.UpdateConsent:output_type -> identity.UpdateConsentResponse
	27, // [27:50] is the sub-list for method output_type
	4,  // [4:27] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   50,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
