// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: transaction.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0}
}

type BankListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Banks         []*BankInfo            `protobuf:"bytes,1,rep,name=banks,proto3" json:"banks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankListResponse) Reset() {
	*x = BankListResponse{}
	mi := &file_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankListResponse) ProtoMessage() {}

func (x *BankListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankListResponse.ProtoReflect.Descriptor instead.
func (*BankListResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *BankListResponse) GetBanks() []*BankInfo {
	if x != nil {
		return x.Banks
	}
	return nil
}

type BankInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankInfo) Reset() {
	*x = BankInfo{}
	mi := &file_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankInfo) ProtoMessage() {}

func (x *BankInfo) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankInfo.ProtoReflect.Descriptor instead.
func (*BankInfo) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *BankInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *BankInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EnquiryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BankCode      string                 `protobuf:"bytes,1,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	AccountNumber string                 `protobuf:"bytes,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnquiryRequest) Reset() {
	*x = EnquiryRequest{}
	mi := &file_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnquiryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnquiryRequest) ProtoMessage() {}

func (x *EnquiryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnquiryRequest.ProtoReflect.Descriptor instead.
func (*EnquiryRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *EnquiryRequest) GetBankCode() string {
	if x != nil {
		return x.BankCode
	}
	return ""
}

func (x *EnquiryRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

type EnquiryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AccountName   string                 `protobuf:"bytes,2,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnquiryResponse) Reset() {
	*x = EnquiryResponse{}
	mi := &file_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnquiryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnquiryResponse) ProtoMessage() {}

func (x *EnquiryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnquiryResponse.ProtoReflect.Descriptor instead.
func (*EnquiryResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *EnquiryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EnquiryResponse) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *EnquiryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    string                 `protobuf:"bytes,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToAccount     string                 `protobuf:"bytes,2,opt,name=to_account,json=toAccount,proto3" json:"to_account,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Pin           string                 `protobuf:"bytes,4,opt,name=pin,proto3" json:"pin,omitempty"`
	Narration     string                 `protobuf:"bytes,5,opt,name=narration,proto3" json:"narration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *TransferRequest) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *TransferRequest) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *TransferRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferRequest) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

func (x *TransferRequest) GetNarration() string {
	if x != nil {
		return x.Narration
	}
	return ""
}

type BankTransferRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	FromUserId          string                 `protobuf:"bytes,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	BankCode            string                 `protobuf:"bytes,2,opt,name=bank_code,json=bankCode,proto3" json:"bank_code,omitempty"`
	AccountNumber       string                 `protobuf:"bytes,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Amount              float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Pin                 string                 `protobuf:"bytes,5,opt,name=pin,proto3" json:"pin,omitempty"`
	Narration           string                 `protobuf:"bytes,6,opt,name=narration,proto3" json:"narration,omitempty"`
	ReceiverName        string                 `protobuf:"bytes,7,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`
	ReceiverPhone       string                 `protobuf:"bytes,8,opt,name=receiver_phone,json=receiverPhone,proto3" json:"receiver_phone,omitempty"`
	ReceiverAccountType string                 `protobuf:"bytes,9,opt,name=receiver_account_type,json=receiverAccountType,proto3" json:"receiver_account_type,omitempty"`
	ReceiverKyc         string                 `protobuf:"bytes,10,opt,name=receiver_kyc,json=receiverKyc,proto3" json:"receiver_kyc,omitempty"`
	ReceiverBvn         string                 `protobuf:"bytes,11,opt,name=receiver_bvn,json=receiverBvn,proto3" json:"receiver_bvn,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BankTransferRequest) Reset() {
	*x = BankTransferRequest{}
	mi := &file_transaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankTransferRequest) ProtoMessage() {}

func (x *BankTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankTransferRequest.ProtoReflect.Descriptor instead.
func (*BankTransferRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *BankTransferRequest) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *BankTransferRequest) GetBankCode() string {
	if x != nil {
		return x.BankCode
	}
	return ""
}

func (x *BankTransferRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *BankTransferRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BankTransferRequest) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

func (x *BankTransferRequest) GetNarration() string {
	if x != nil {
		return x.Narration
	}
	return ""
}

func (x *BankTransferRequest) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *BankTransferRequest) GetReceiverPhone() string {
	if x != nil {
		return x.ReceiverPhone
	}
	return ""
}

func (x *BankTransferRequest) GetReceiverAccountType() string {
	if x != nil {
		return x.ReceiverAccountType
	}
	return ""
}

func (x *BankTransferRequest) GetReceiverKyc() string {
	if x != nil {
		return x.ReceiverKyc
	}
	return ""
}

func (x *BankTransferRequest) GetReceiverBvn() string {
	if x != nil {
		return x.ReceiverBvn
	}
	return ""
}

type TSQRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reference     string                 `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TSQRequest) Reset() {
	*x = TSQRequest{}
	mi := &file_transaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TSQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TSQRequest) ProtoMessage() {}

func (x *TSQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TSQRequest.ProtoReflect.Descriptor instead.
func (*TSQRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{7}
}

func (x *TSQRequest) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *TSQRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *TSQRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type TransferResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TransactionRef string                 `protobuf:"bytes,3,opt,name=transaction_ref,json=transactionRef,proto3" json:"transaction_ref,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_transaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{8}
}

func (x *TransferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransferResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TransferResponse) GetTransactionRef() string {
	if x != nil {
		return x.TransactionRef
	}
	return ""
}

type HistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_transaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{9}
}

func (x *HistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*TransactionInfo     `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_transaction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{10}
}

func (x *HistoryResponse) GetTransactions() []*TransactionInfo {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type TransactionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Narration     string                 `protobuf:"bytes,6,opt,name=narration,proto3" json:"narration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionInfo) Reset() {
	*x = TransactionInfo{}
	mi := &file_transaction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionInfo) ProtoMessage() {}

func (x *TransactionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionInfo.ProtoReflect.Descriptor instead.
func (*TransactionInfo) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{11}
}

func (x *TransactionInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransactionInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TransactionInfo) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransactionInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TransactionInfo) GetNarration() string {
	if x != nil {
		return x.Narration
	}
	return ""
}

var File_transaction_proto protoreflect.FileDescriptor

const file_transaction_proto_rawDesc = "" +
	"\n" +
	"\x11transaction.proto\x12\vtransaction\"\a\n" +
	"\x05Empty\"?\n" +
	"\x10BankListResponse\x12+\n" +
	"\x05banks\x18\x01 \x03(\v2\x15.transaction.BankInfoR\x05banks\"2\n" +
	"\bBankInfo\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"T\n" +
	"\x0eEnquiryRequest\x12\x1b\n" +
	"\tbank_code\x18\x01 \x01(\tR\bbankCode\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\tR\raccountNumber\"h\n" +
	"\x0fEnquiryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\faccount_name\x18\x02 \x01(\tR\vaccountName\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x9a\x01\n" +
	"\x0fTransferRequest\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\tR\n" +
	"fromUserId\x12\x1d\n" +
	"\n" +
	"to_account\x18\x02 \x01(\tR\ttoAccount\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x10\n" +
	"\x03pin\x18\x04 \x01(\tR\x03pin\x12\x1c\n" +
	"\tnarration\x18\x05 \x01(\tR\tnarration\"\x89\x03\n" +
	"\x13BankTransferRequest\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\tR\n" +
	"fromUserId\x12\x1b\n" +
	"\tbank_code\x18\x02 \x01(\tR\bbankCode\x12%\n" +
	"\x0eaccount_number\x18\x03 \x01(\tR\raccountNumber\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x10\n" +
	"\x03pin\x18\x05 \x01(\tR\x03pin\x12\x1c\n" +
	"\tnarration\x18\x06 \x01(\tR\tnarration\x12#\n" +
	"\rreceiver_name\x18\a \x01(\tR\freceiverName\x12%\n" +
	"\x0ereceiver_phone\x18\b \x01(\tR\rreceiverPhone\x122\n" +
	"\x15receiver_account_type\x18\t \x01(\tR\x13receiverAccountType\x12!\n" +
	"\freceiver_kyc\x18\n" +
	" \x01(\tR\vreceiverKyc\x12!\n" +
	"\freceiver_bvn\x18\v \x01(\tR\vreceiverBvn\"V\n" +
	"\n" +
	"TSQRequest\x12\x1c\n" +
	"\treference\x18\x01 \x01(\tR\treference\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"o\n" +
	"\x10TransferResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0ftransaction_ref\x18\x03 \x01(\tR\x0etransactionRef\")\n" +
	"\x0eHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"S\n" +
	"\x0fHistoryResponse\x12@\n" +
	"\ftransactions\x18\x01 \x03(\v2\x1c.transaction.TransactionInfoR\ftransactions\"\xa2\x01\n" +
	"\x0fTransactionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tnarration\x18\x06 \x01(\tR\tnarration2\xf7\x03\n" +
	"\x12TransactionService\x12Q\n" +
	"\x10TransferInternal\x12\x1c.transaction.TransferRequest\x1a\x1d.transaction.TransferResponse\"\x00\x12Q\n" +
	"\fTransferBank\x12 .transaction.BankTransferRequest\x1a\x1d.transaction.TransferResponse\"\x00\x12T\n" +
	"\x15GetTransactionHistory\x12\x1b.transaction.HistoryRequest\x1a\x1c.transaction.HistoryResponse\"\x00\x12B\n" +
	"\vGetBankList\x12\x12.transaction.Empty\x1a\x1d.transaction.BankListResponse\"\x00\x12M\n" +
	"\x0eAccountEnquiry\x12\x1b.transaction.EnquiryRequest\x1a\x1c.transaction.EnquiryResponse\"\x00\x12R\n" +
	"\x16TransactionStatusQuery\x12\x17.transaction.TSQRequest\x1a\x1d.transaction.TransferResponse\"\x00B*Z(github.com/gdl/transaction-service/protob\x06proto3"

var (
	file_transaction_proto_rawDescOnce sync.Once
	file_transaction_proto_rawDescData []byte
)

func file_transaction_proto_rawDescGZIP() []byte {
	file_transaction_proto_rawDescOnce.Do(func() {
		file_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)))
	})
	return file_transaction_proto_rawDescData
}

var file_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_transaction_proto_goTypes = []any{
	(*Empty)(nil),               // 0: transaction.Empty
	(*BankListResponse)(nil),    // 1: transaction.BankListResponse
	(*BankInfo)(nil),            // 2: transaction.BankInfo
	(*EnquiryRequest)(nil),      // 3: transaction.EnquiryRequest
	(*EnquiryResponse)(nil),     // 4: transaction.EnquiryResponse
	(*TransferRequest)(nil),     // 5: transaction.TransferRequest
	(*BankTransferRequest)(nil), // 6: transaction.BankTransferRequest
	(*TSQRequest)(nil),          // 7: transaction.TSQRequest
	(*TransferResponse)(nil),    // 8: transaction.TransferResponse
	(*HistoryRequest)(nil),      // 9: transaction.HistoryRequest
	(*HistoryResponse)(nil),     // 10: transaction.HistoryResponse
	(*TransactionInfo)(nil),     // 11: transaction.TransactionInfo
}
var file_transaction_proto_depIdxs = []int32{
	2,  // 0: transaction.BankListResponse.banks:type_name -> transaction.BankInfo
	11, // 1: transaction.HistoryResponse.transactions:type_name -> transaction.TransactionInfo
	5,  // 2: transaction.TransactionService.TransferInternal:input_type -> transaction.TransferRequest
	6,  // 3: transaction.TransactionService.TransferBank:input_type -> transaction.BankTransferRequest
	9,  // 4: transaction.TransactionService.GetTransactionHistory:input_type -> transaction.HistoryRequest
	0,  // 5: transaction.TransactionService.GetBankList:input_type -> transaction.Empty
	3,  // 6: transaction.TransactionService.AccountEnquiry:input_type -> transaction.EnquiryRequest
	7,  // 7: transaction.TransactionService.TransactionStatusQuery:input_type -> transaction.TSQRequest
	8,  // 8: transaction.TransactionService.TransferInternal:output_type -> transaction.TransferResponse
	8,  // 9: transaction.TransactionService.TransferBank:output_type -> transaction.TransferResponse
	10, // 10: transaction.TransactionService.GetTransactionHistory:output_type -> transaction.HistoryResponse
	1,  // 11: transaction.TransactionService.GetBankList:output_type -> transaction.BankListResponse
	4,  // 12: transaction.TransactionService.AccountEnquiry:output_type -> transaction.EnquiryResponse
	8,  // 13: transaction.TransactionService.TransactionStatusQuery:output_type -> transaction.TransferResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_transaction_proto_init() }
func file_transaction_proto_init() {
	if File_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_proto_goTypes,
		DependencyIndexes: file_transaction_proto_depIdxs,
		MessageInfos:      file_transaction_proto_msgTypes,
	}.Build()
	File_transaction_proto = out.File
	file_transaction_proto_goTypes = nil
	file_transaction_proto_depIdxs = nil
}
