// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/reporting.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DashboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuperAdmin  bool                   `protobuf:"varint,1,opt,name=is_super_admin,json=isSuperAdmin,proto3" json:"is_super_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardRequest) Reset() {
	*x = DashboardRequest{}
	mi := &file_proto_reporting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardRequest) ProtoMessage() {}

func (x *DashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reporting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardRequest.ProtoReflect.Descriptor instead.
func (*DashboardRequest) Descriptor() ([]byte, []int) {
	return file_proto_reporting_proto_rawDescGZIP(), []int{0}
}

func (x *DashboardRequest) GetIsSuperAdmin() bool {
	if x != nil {
		return x.IsSuperAdmin
	}
	return false
}

type DashboardResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Flexi           *FlexiStats            `protobuf:"bytes,1,opt,name=flexi,proto3" json:"flexi,omitempty"`
	AssetManagement *AssetStats            `protobuf:"bytes,2,opt,name=asset_management,json=assetManagement,proto3" json:"asset_management,omitempty"`
	General         *GeneralStats          `protobuf:"bytes,3,opt,name=general,proto3" json:"general,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DashboardResponse) Reset() {
	*x = DashboardResponse{}
	mi := &file_proto_reporting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardResponse) ProtoMessage() {}

func (x *DashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reporting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardResponse.ProtoReflect.Descriptor instead.
func (*DashboardResponse) Descriptor() ([]byte, []int) {
	return file_proto_reporting_proto_rawDescGZIP(), []int{1}
}

func (x *DashboardResponse) GetFlexi() *FlexiStats {
	if x != nil {
		return x.Flexi
	}
	return nil
}

func (x *DashboardResponse) GetAssetManagement() *AssetStats {
	if x != nil {
		return x.AssetManagement
	}
	return nil
}

func (x *DashboardResponse) GetGeneral() *GeneralStats {
	if x != nil {
		return x.General
	}
	return nil
}

type FlexiStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PendingAmount   float64                `protobuf:"fixed64,1,opt,name=pending_amount,json=pendingAmount,proto3" json:"pending_amount,omitempty"`
	DisbursedAmount float64                `protobuf:"fixed64,2,opt,name=disbursed_amount,json=disbursedAmount,proto3" json:"disbursed_amount,omitempty"`
	RejectedAmount  float64                `protobuf:"fixed64,3,opt,name=rejected_amount,json=rejectedAmount,proto3" json:"rejected_amount,omitempty"`
	Trend           float64                `protobuf:"fixed64,4,opt,name=trend,proto3" json:"trend,omitempty"`
	PendingCount    int32                  `protobuf:"varint,5,opt,name=pending_count,json=pendingCount,proto3" json:"pending_count,omitempty"`
	DisbursedCount  int32                  `protobuf:"varint,6,opt,name=disbursed_count,json=disbursedCount,proto3" json:"disbursed_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FlexiStats) Reset() {
	*x = FlexiStats{}
	mi := &file_proto_reporting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlexiStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlexiStats) ProtoMessage() {}

func (x *FlexiStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reporting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlexiStats.ProtoReflect.Descriptor instead.
func (*FlexiStats) Descriptor() ([]byte, []int) {
	return file_proto_reporting_proto_rawDescGZIP(), []int{2}
}

func (x *FlexiStats) GetPendingAmount() float64 {
	if x != nil {
		return x.PendingAmount
	}
	return 0
}

func (x *FlexiStats) GetDisbursedAmount() float64 {
	if x != nil {
		return x.DisbursedAmount
	}
	return 0
}

func (x *FlexiStats) GetRejectedAmount() float64 {
	if x != nil {
		return x.RejectedAmount
	}
	return 0
}

func (x *FlexiStats) GetTrend() float64 {
	if x != nil {
		return x.Trend
	}
	return 0
}

func (x *FlexiStats) GetPendingCount() int32 {
	if x != nil {
		return x.PendingCount
	}
	return 0
}

func (x *FlexiStats) GetDisbursedCount() int32 {
	if x != nil {
		return x.DisbursedCount
	}
	return 0
}

type AssetStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalAum         float64                `protobuf:"fixed64,1,opt,name=total_aum,json=totalAum,proto3" json:"total_aum,omitempty"`
	TotalSubscribers int32                  `protobuf:"varint,2,opt,name=total_subscribers,json=totalSubscribers,proto3" json:"total_subscribers,omitempty"`
	MmfValue         float64                `protobuf:"fixed64,3,opt,name=mmf_value,json=mmfValue,proto3" json:"mmf_value,omitempty"`
	CanaryValue      float64                `protobuf:"fixed64,4,opt,name=canary_value,json=canaryValue,proto3" json:"canary_value,omitempty"`
	IncomeValue      float64                `protobuf:"fixed64,5,opt,name=income_value,json=incomeValue,proto3" json:"income_value,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AssetStats) Reset() {
	*x = AssetStats{}
	mi := &file_proto_reporting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetStats) ProtoMessage() {}

func (x *AssetStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reporting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetStats.ProtoReflect.Descriptor instead.
func (*AssetStats) Descriptor() ([]byte, []int) {
	return file_proto_reporting_proto_rawDescGZIP(), []int{3}
}

func (x *AssetStats) GetTotalAum() float64 {
	if x != nil {
		return x.TotalAum
	}
	return 0
}

func (x *AssetStats) GetTotalSubscribers() int32 {
	if x != nil {
		return x.TotalSubscribers
	}
	return 0
}

func (x *AssetStats) GetMmfValue() float64 {
	if x != nil {
		return x.MmfValue
	}
	return 0
}

func (x *AssetStats) GetCanaryValue() float64 {
	if x != nil {
		return x.CanaryValue
	}
	return 0
}

func (x *AssetStats) GetIncomeValue() float64 {
	if x != nil {
		return x.IncomeValue
	}
	return 0
}

type GeneralStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalUsers    int32                  `protobuf:"varint,1,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	GrowthTrend   float64                `protobuf:"fixed64,2,opt,name=growth_trend,json=growthTrend,proto3" json:"growth_trend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneralStats) Reset() {
	*x = GeneralStats{}
	mi := &file_proto_reporting_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneralStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralStats) ProtoMessage() {}

func (x *GeneralStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reporting_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralStats.ProtoReflect.Descriptor instead.
func (*GeneralStats) Descriptor() ([]byte, []int) {
	return file_proto_reporting_proto_rawDescGZIP(), []int{4}
}

func (x *GeneralStats) GetTotalUsers() int32 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *GeneralStats) GetGrowthTrend() float64 {
	if x != nil {
		return x.GrowthTrend
	}
	return 0
}

type UserGrowthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          int32                  `protobuf:"varint,1,opt,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGrowthRequest) Reset() {
	*x = UserGrowthRequest{}
	mi := &file_proto_reporting_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGrowthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGrowthRequest) ProtoMessage() {}

func (x *UserGrowthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reporting_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGrowthRequest.ProtoReflect.Descriptor instead.
func (*UserGrowthRequest) Descriptor() ([]byte, []int) {
	return file_proto_reporting_proto_rawDescGZIP(), []int{5}
}

func (x *UserGrowthRequest) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

type UserGrowthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*GrowthPoint         `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGrowthResponse) Reset() {
	*x = UserGrowthResponse{}
	mi := &file_proto_reporting_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGrowthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGrowthResponse) ProtoMessage() {}

func (x *UserGrowthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reporting_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGrowthResponse.ProtoReflect.Descriptor instead.
func (*UserGrowthResponse) Descriptor() ([]byte, []int) {
	return file_proto_reporting_proto_rawDescGZIP(), []int{6}
}

func (x *UserGrowthResponse) GetPoints() []*GrowthPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type GrowthPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrowthPoint) Reset() {
	*x = GrowthPoint{}
	mi := &file_proto_reporting_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrowthPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrowthPoint) ProtoMessage() {}

func (x *GrowthPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reporting_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrowthPoint.ProtoReflect.Descriptor instead.
func (*GrowthPoint) Descriptor() ([]byte, []int) {
	return file_proto_reporting_proto_rawDescGZIP(), []int{7}
}

func (x *GrowthPoint) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GrowthPoint) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_proto_reporting_proto protoreflect.FileDescriptor

const file_proto_reporting_proto_rawDesc = "" +
	"\n" +
	"\x15proto/reporting.proto\x12\treporting\"8\n" +
	"\x10DashboardRequest\x12$\n" +
	"\x0eis_super_admin\x18\x01 \x01(\bR\fisSuperAdmin\"\xb5\x01\n" +
	"\x11DashboardResponse\x12+\n" +
	"\x05flexi\x18\x01 \x01(\v2\x15.reporting.FlexiStatsR\x05flexi\x12@\n" +
	"\x10asset_management\x18\x02 \x01(\v2\x15.reporting.AssetStatsR\x0fassetManagement\x121\n" +
	"\ageneral\x18\x03 \x01(\v2\x17.reporting.GeneralStatsR\ageneral\"\xeb\x01\n" +
	"\n" +
	"FlexiStats\x12%\n" +
	"\x0epending_amount\x18\x01 \x01(\x01R\rpendingAmount\x12)\n" +
	"\x10disbursed_amount\x18\x02 \x01(\x01R\x0fdisbursedAmount\x12'\n" +
	"\x0frejected_amount\x18\x03 \x01(\x01R\x0erejectedAmount\x12\x14\n" +
	"\x05trend\x18\x04 \x01(\x01R\x05trend\x12#\n" +
	"\rpending_count\x18\x05 \x01(\x05R\fpendingCount\x12'\n" +
	"\x0fdisbursed_count\x18\x06 \x01(\x05R\x0edisbursedCount\"\xb9\x01\n" +
	"\n" +
	"AssetStats\x12\x1b\n" +
	"\ttotal_aum\x18\x01 \x01(\x01R\btotalAum\x12+\n" +
	"\x11total_subscribers\x18\x02 \x01(\x05R\x10totalSubscribers\x12\x1b\n" +
	"\tmmf_value\x18\x03 \x01(\x01R\bmmfValue\x12!\n" +
	"\fcanary_value\x18\x04 \x01(\x01R\vcanaryValue\x12!\n" +
	"\fincome_value\x18\x05 \x01(\x01R\vincomeValue\"R\n" +
	"\fGeneralStats\x12\x1f\n" +
	"\vtotal_users\x18\x01 \x01(\x05R\n" +
	"totalUsers\x12!\n" +
	"\fgrowth_trend\x18\x02 \x01(\x01R\vgrowthTrend\"'\n" +
	"\x11UserGrowthRequest\x12\x12\n" +
	"\x04days\x18\x01 \x01(\x05R\x04days\"D\n" +
	"\x12UserGrowthResponse\x12.\n" +
	"\x06points\x18\x01 \x03(\v2\x16.reporting.GrowthPointR\x06points\"7\n" +
	"\vGrowthPoint\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count2\xb0\x01\n" +
	"\x10ReportingService\x12N\n" +
	"\x11GetDashboardStats\x12\x1b.reporting.DashboardRequest\x1a\x1c.reporting.DashboardResponse\x12L\n" +
	"\rGetUserGrowth\x12\x1c.reporting.UserGrowthRequest\x1a\x1d.reporting.UserGrowthResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_reporting_proto_rawDescOnce sync.Once
	file_proto_reporting_proto_rawDescData []byte
)

func file_proto_reporting_proto_rawDescGZIP() []byte {
	file_proto_reporting_proto_rawDescOnce.Do(func() {
		file_proto_reporting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_reporting_proto_rawDesc), len(file_proto_reporting_proto_rawDesc)))
	})
	return file_proto_reporting_proto_rawDescData
}

var file_proto_reporting_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_reporting_proto_goTypes = []any{
	(*DashboardRequest)(nil),   // 0: reporting.DashboardRequest
	(*DashboardResponse)(nil),  // 1: reporting.DashboardResponse
	(*FlexiStats)(nil),         // 2: reporting.FlexiStats
	(*AssetStats)(nil),         // 3: reporting.AssetStats
	(*GeneralStats)(nil),       // 4: reporting.GeneralStats
	(*UserGrowthRequest)(nil),  // 5: reporting.UserGrowthRequest
	(*UserGrowthResponse)(nil), // 6: reporting.UserGrowthResponse
	(*GrowthPoint)(nil),        // 7: reporting.GrowthPoint
}
var file_proto_reporting_proto_depIdxs = []int32{
	2, // 0: reporting.DashboardResponse.flexi:type_name -> reporting.FlexiStats
	3, // 1: reporting.DashboardResponse.asset_management:type_name -> reporting.AssetStats
	4, // 2: reporting.DashboardResponse.general:type_name -> reporting.GeneralStats
	7, // 3: reporting.UserGrowthResponse.points:type_name -> reporting.GrowthPoint
	0, // 4: reporting.ReportingService.GetDashboardStats:input_type -> reporting.DashboardRequest
	5, // 5: reporting.ReportingService.GetUserGrowth:input_type -> reporting.UserGrowthRequest
	1, // 6: reporting.ReportingService.GetDashboardStats:output_type -> reporting.DashboardResponse
	6, // 7: reporting.ReportingService.GetUserGrowth:output_type -> reporting.UserGrowthResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_reporting_proto_init() }
func file_proto_reporting_proto_init() {
	if File_proto_reporting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_reporting_proto_rawDesc), len(file_proto_reporting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_reporting_proto_goTypes,
		DependencyIndexes: file_proto_reporting_proto_depIdxs,
		MessageInfos:      file_proto_reporting_proto_msgTypes,
	}.Build()
	File_proto_reporting_proto = out.File
	file_proto_reporting_proto_goTypes = nil
	file_proto_reporting_proto_depIdxs = nil
}
