export enum FlexiRequestType {
  GENERAL_REQUEST = 'GENERAL_REQUEST',
  FUNDING = 'FUNDING',
  RECALL = 'RECALL',
}

export enum FlexiRequestStatus {
  PENDING_DOCS = 'PENDING_DOCS',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  DISBURSED = 'DISBURSED',
  COMPLETED = 'COMPLETED',
}
