// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: bankone.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_bankone_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_bankone_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_bankone_proto_rawDescGZIP(), []int{0}
}

type InterbankTransferRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Amount                string                 `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"` // in Naira, will be converted to Kobo in connector
	PayerAccountNumber    string                 `protobuf:"bytes,2,opt,name=payer_account_number,json=payerAccountNumber,proto3" json:"payer_account_number,omitempty"`
	PayerName             string                 `protobuf:"bytes,3,opt,name=payer_name,json=payerName,proto3" json:"payer_name,omitempty"`
	ReceiverBankCode      string                 `protobuf:"bytes,4,opt,name=receiver_bank_code,json=receiverBankCode,proto3" json:"receiver_bank_code,omitempty"`
	ReceiverAccountNumber string                 `protobuf:"bytes,5,opt,name=receiver_account_number,json=receiverAccountNumber,proto3" json:"receiver_account_number,omitempty"`
	ReceiverName          string                 `protobuf:"bytes,6,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`
	ReceiverPhoneNumber   string                 `protobuf:"bytes,7,opt,name=receiver_phone_number,json=receiverPhoneNumber,proto3" json:"receiver_phone_number,omitempty"`
	ReceiverAccountType   string                 `protobuf:"bytes,8,opt,name=receiver_account_type,json=receiverAccountType,proto3" json:"receiver_account_type,omitempty"`
	ReceiverKyc           string                 `protobuf:"bytes,9,opt,name=receiver_kyc,json=receiverKyc,proto3" json:"receiver_kyc,omitempty"`
	ReceiverBvn           string                 `protobuf:"bytes,10,opt,name=receiver_bvn,json=receiverBvn,proto3" json:"receiver_bvn,omitempty"`
	Narration             string                 `protobuf:"bytes,11,opt,name=narration,proto3" json:"narration,omitempty"`
	Reference             string                 `protobuf:"bytes,12,opt,name=reference,proto3" json:"reference,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *InterbankTransferRequest) Reset() {
	*x = InterbankTransferRequest{}
	mi := &file_bankone_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterbankTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterbankTransferRequest) ProtoMessage() {}

func (x *InterbankTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bankone_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterbankTransferRequest.ProtoReflect.Descriptor instead.
func (*InterbankTransferRequest) Descriptor() ([]byte, []int) {
	return file_bankone_proto_rawDescGZIP(), []int{1}
}

func (x *InterbankTransferRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *InterbankTransferRequest) GetPayerAccountNumber() string {
	if x != nil {
		return x.PayerAccountNumber
	}
	return ""
}

func (x *InterbankTransferRequest) GetPayerName() string {
	if x != nil {
		return x.PayerName
	}
	return ""
}

func (x *InterbankTransferRequest) GetReceiverBankCode() string {
	if x != nil {
		return x.ReceiverBankCode
	}
	return ""
}

func (x *InterbankTransferRequest) GetReceiverAccountNumber() string {
	if x != nil {
		return x.ReceiverAccountNumber
	}
	return ""
}

func (x *InterbankTransferRequest) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *InterbankTransferRequest) GetReceiverPhoneNumber() string {
	if x != nil {
		return x.ReceiverPhoneNumber
	}
	return ""
}

func (x *InterbankTransferRequest) GetReceiverAccountType() string {
	if x != nil {
		return x.ReceiverAccountType
	}
	return ""
}

func (x *InterbankTransferRequest) GetReceiverKyc() string {
	if x != nil {
		return x.ReceiverKyc
	}
	return ""
}

func (x *InterbankTransferRequest) GetReceiverBvn() string {
	if x != nil {
		return x.ReceiverBvn
	}
	return ""
}

func (x *InterbankTransferRequest) GetNarration() string {
	if x != nil {
		return x.Narration
	}
	return ""
}

func (x *InterbankTransferRequest) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

type TSQRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RetrievalReference string                 `protobuf:"bytes,1,opt,name=retrieval_reference,json=retrievalReference,proto3" json:"retrieval_reference,omitempty"`
	TransactionDate    string                 `protobuf:"bytes,2,opt,name=transaction_date,json=transactionDate,proto3" json:"transaction_date,omitempty"` // YYYY-MM-DD
	TransactionType    string                 `protobuf:"bytes,3,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"`
	Amount             string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"` // in Naira
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TSQRequest) Reset() {
	*x = TSQRequest{}
	mi := &file_bankone_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TSQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TSQRequest) ProtoMessage() {}

func (x *TSQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bankone_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TSQRequest.ProtoReflect.Descriptor instead.
func (*TSQRequest) Descriptor() ([]byte, []int) {
	return file_bankone_proto_rawDescGZIP(), []int{2}
}

func (x *TSQRequest) GetRetrievalReference() string {
	if x != nil {
		return x.RetrievalReference
	}
	return ""
}

func (x *TSQRequest) GetTransactionDate() string {
	if x != nil {
		return x.TransactionDate
	}
	return ""
}

func (x *TSQRequest) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *TSQRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type CreateAccountQuickRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	AccountType   string                 `protobuf:"bytes,5,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountQuickRequest) Reset() {
	*x = CreateAccountQuickRequest{}
	mi := &file_bankone_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountQuickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountQuickRequest) ProtoMessage() {}

func (x *CreateAccountQuickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bankone_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountQuickRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountQuickRequest) Descriptor() ([]byte, []int) {
	return file_bankone_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAccountQuickRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateAccountQuickRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateAccountQuickRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateAccountQuickRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateAccountQuickRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

type CreateCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomerRequest) Reset() {
	*x = CreateCustomerRequest{}
	mi := &file_bankone_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerRequest) ProtoMessage() {}

func (x *CreateCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bankone_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerRequest.ProtoReflect.Descriptor instead.
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) {
	return file_bankone_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCustomerRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateCustomerRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateCustomerRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateCustomerRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type BalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber string                 `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceRequest) Reset() {
	*x = BalanceRequest{}
	mi := &file_bankone_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceRequest) ProtoMessage() {}

func (x *BalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bankone_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceRequest.ProtoReflect.Descriptor instead.
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return file_bankone_proto_rawDescGZIP(), []int{5}
}

func (x *BalanceRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

type BalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceResponse) Reset() {
	*x = BalanceResponse{}
	mi := &file_bankone_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceResponse) ProtoMessage() {}

func (x *BalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bankone_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceResponse.ProtoReflect.Descriptor instead.
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return file_bankone_proto_rawDescGZIP(), []int{6}
}

func (x *BalanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BalanceResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *BalanceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber string                 `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	FromDate      string                 `protobuf:"bytes,2,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate        string                 `protobuf:"bytes,3,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionsRequest) Reset() {
	*x = TransactionsRequest{}
	mi := &file_bankone_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionsRequest) ProtoMessage() {}

func (x *TransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bankone_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionsRequest.ProtoReflect.Descriptor instead.
func (*TransactionsRequest) Descriptor() ([]byte, []int) {
	return file_bankone_proto_rawDescGZIP(), []int{7}
}

func (x *TransactionsRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *TransactionsRequest) GetFromDate() string {
	if x != nil {
		return x.FromDate
	}
	return ""
}

func (x *TransactionsRequest) GetToDate() string {
	if x != nil {
		return x.ToDate
	}
	return ""
}

type TransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Transactions  []*TransactionInfo     `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionsResponse) Reset() {
	*x = TransactionsResponse{}
	mi := &file_bankone_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionsResponse) ProtoMessage() {}

func (x *TransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bankone_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionsResponse.ProtoReflect.Descriptor instead.
func (*TransactionsResponse) Descriptor() ([]byte, []int) {
	return file_bankone_proto_rawDescGZIP(), []int{8}
}

func (x *TransactionsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransactionsResponse) GetTransactions() []*TransactionInfo {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type TransactionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        string                 `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Reference     string                 `protobuf:"bytes,4,opt,name=reference,proto3" json:"reference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionInfo) Reset() {
	*x = TransactionInfo{}
	mi := &file_bankone_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionInfo) ProtoMessage() {}

func (x *TransactionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bankone_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionInfo.ProtoReflect.Descriptor instead.
func (*TransactionInfo) Descriptor() ([]byte, []int) {
	return file_bankone_proto_rawDescGZIP(), []int{9}
}

func (x *TransactionInfo) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *TransactionInfo) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *TransactionInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TransactionInfo) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

type AccountEnquiryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber string                 `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountEnquiryRequest) Reset() {
	*x = AccountEnquiryRequest{}
	mi := &file_bankone_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountEnquiryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountEnquiryRequest) ProtoMessage() {}

func (x *AccountEnquiryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bankone_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountEnquiryRequest.ProtoReflect.Descriptor instead.
func (*AccountEnquiryRequest) Descriptor() ([]byte, []int) {
	return file_bankone_proto_rawDescGZIP(), []int{10}
}

func (x *AccountEnquiryRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

type PNDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber string                 `protobuf:"bytes,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PNDRequest) Reset() {
	*x = PNDRequest{}
	mi := &file_bankone_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PNDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PNDRequest) ProtoMessage() {}

func (x *PNDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bankone_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PNDRequest.ProtoReflect.Descriptor instead.
func (*PNDRequest) Descriptor() ([]byte, []int) {
	return file_bankone_proto_rawDescGZIP(), []int{11}
}

func (x *PNDRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *PNDRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type LienRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber string                 `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LienRequest) Reset() {
	*x = LienRequest{}
	mi := &file_bankone_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LienRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LienRequest) ProtoMessage() {}

func (x *LienRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bankone_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LienRequest.ProtoReflect.Descriptor instead.
func (*LienRequest) Descriptor() ([]byte, []int) {
	return file_bankone_proto_rawDescGZIP(), []int{12}
}

func (x *LienRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *LienRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *LienRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type BVNRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bvn           string                 `protobuf:"bytes,1,opt,name=bvn,proto3" json:"bvn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BVNRequest) Reset() {
	*x = BVNRequest{}
	mi := &file_bankone_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BVNRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BVNRequest) ProtoMessage() {}

func (x *BVNRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bankone_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BVNRequest.ProtoReflect.Descriptor instead.
func (*BVNRequest) Descriptor() ([]byte, []int) {
	return file_bankone_proto_rawDescGZIP(), []int{13}
}

func (x *BVNRequest) GetBvn() string {
	if x != nil {
		return x.Bvn
	}
	return ""
}

type BankOneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // JSON encoded response from BankOne
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankOneResponse) Reset() {
	*x = BankOneResponse{}
	mi := &file_bankone_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankOneResponse) ProtoMessage() {}

func (x *BankOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bankone_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankOneResponse.ProtoReflect.Descriptor instead.
func (*BankOneResponse) Descriptor() ([]byte, []int) {
	return file_bankone_proto_rawDescGZIP(), []int{14}
}

func (x *BankOneResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BankOneResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BankOneResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_bankone_proto protoreflect.FileDescriptor

const file_bankone_proto_rawDesc = "" +
	"\n" +
	"\rbankone.proto\x12\abankone\"\a\n" +
	"\x05Empty\"\xf8\x03\n" +
	"\x18InterbankTransferRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\tR\x06amount\x120\n" +
	"\x14payer_account_number\x18\x02 \x01(\tR\x12payerAccountNumber\x12\x1d\n" +
	"\n" +
	"payer_name\x18\x03 \x01(\tR\tpayerName\x12,\n" +
	"\x12receiver_bank_code\x18\x04 \x01(\tR\x10receiverBankCode\x126\n" +
	"\x17receiver_account_number\x18\x05 \x01(\tR\x15receiverAccountNumber\x12#\n" +
	"\rreceiver_name\x18\x06 \x01(\tR\freceiverName\x122\n" +
	"\x15receiver_phone_number\x18\a \x01(\tR\x13receiverPhoneNumber\x122\n" +
	"\x15receiver_account_type\x18\b \x01(\tR\x13receiverAccountType\x12!\n" +
	"\freceiver_kyc\x18\t \x01(\tR\vreceiverKyc\x12!\n" +
	"\freceiver_bvn\x18\n" +
	" \x01(\tR\vreceiverBvn\x12\x1c\n" +
	"\tnarration\x18\v \x01(\tR\tnarration\x12\x1c\n" +
	"\treference\x18\f \x01(\tR\treference\"\xab\x01\n" +
	"\n" +
	"TSQRequest\x12/\n" +
	"\x13retrieval_reference\x18\x01 \x01(\tR\x12retrievalReference\x12)\n" +
	"\x10transaction_date\x18\x02 \x01(\tR\x0ftransactionDate\x12)\n" +
	"\x10transaction_type\x18\x03 \x01(\tR\x0ftransactionType\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\"\xa6\x01\n" +
	"\x19CreateAccountQuickRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12!\n" +
	"\faccount_type\x18\x05 \x01(\tR\vaccountType\"\x7f\n" +
	"\x15CreateCustomerRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"7\n" +
	"\x0eBalanceRequest\x12%\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\raccountNumber\"_\n" +
	"\x0fBalanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"r\n" +
	"\x13TransactionsRequest\x12%\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\raccountNumber\x12\x1b\n" +
	"\tfrom_date\x18\x02 \x01(\tR\bfromDate\x12\x17\n" +
	"\ato_date\x18\x03 \x01(\tR\x06toDate\"n\n" +
	"\x14TransactionsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12<\n" +
	"\ftransactions\x18\x02 \x03(\v2\x18.bankone.TransactionInfoR\ftransactions\"}\n" +
	"\x0fTransactionInfo\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\tR\x06amount\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1c\n" +
	"\treference\x18\x04 \x01(\tR\treference\">\n" +
	"\x15AccountEnquiryRequest\x12%\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\raccountNumber\"K\n" +
	"\n" +
	"PNDRequest\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\tR\raccountNumber\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\"d\n" +
	"\vLienRequest\x12%\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\raccountNumber\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\"\x1e\n" +
	"\n" +
	"BVNRequest\x12\x10\n" +
	"\x03bvn\x18\x01 \x01(\tR\x03bvn\"Y\n" +
	"\x0fBankOneResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data2\xa4\x06\n" +
	"\x0eBankOneService\x12R\n" +
	"\x12CreateAccountQuick\x12\".bankone.CreateAccountQuickRequest\x1a\x18.bankone.BankOneResponse\x12T\n" +
	"\x18CreateCustomerAndAccount\x12\x1e.bankone.CreateCustomerRequest\x1a\x18.bankone.BankOneResponse\x12?\n" +
	"\n" +
	"GetBalance\x12\x17.bankone.BalanceRequest\x1a\x18.bankone.BalanceResponse\x12N\n" +
	"\x0fGetTransactions\x12\x1c.bankone.TransactionsRequest\x1a\x1d.bankone.TransactionsResponse\x12J\n" +
	"\x0eAccountEnquiry\x12\x1e.bankone.AccountEnquiryRequest\x1a\x18.bankone.BankOneResponse\x127\n" +
	"\x06SetPND\x12\x13.bankone.PNDRequest\x1a\x18.bankone.BankOneResponse\x129\n" +
	"\aSetLien\x12\x14.bankone.LienRequest\x1a\x18.bankone.BankOneResponse\x12>\n" +
	"\rGetBVNDetails\x12\x13.bankone.BVNRequest\x1a\x18.bankone.BankOneResponse\x12P\n" +
	"\x11InterbankTransfer\x12!.bankone.InterbankTransferRequest\x1a\x18.bankone.BankOneResponse\x12G\n" +
	"\x16TransactionStatusQuery\x12\x13.bankone.TSQRequest\x1a\x18.bankone.BankOneResponse\x12<\n" +
	"\x10GetOtherBankList\x12\x0e.bankone.Empty\x1a\x18.bankone.BankOneResponseB(Z&github.com/gdl/bankone-connector/protob\x06proto3"

var (
	file_bankone_proto_rawDescOnce sync.Once
	file_bankone_proto_rawDescData []byte
)

func file_bankone_proto_rawDescGZIP() []byte {
	file_bankone_proto_rawDescOnce.Do(func() {
		file_bankone_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bankone_proto_rawDesc), len(file_bankone_proto_rawDesc)))
	})
	return file_bankone_proto_rawDescData
}

var file_bankone_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_bankone_proto_goTypes = []any{
	(*Empty)(nil),                     // 0: bankone.Empty
	(*InterbankTransferRequest)(nil),  // 1: bankone.InterbankTransferRequest
	(*TSQRequest)(nil),                // 2: bankone.TSQRequest
	(*CreateAccountQuickRequest)(nil), // 3: bankone.CreateAccountQuickRequest
	(*CreateCustomerRequest)(nil),     // 4: bankone.CreateCustomerRequest
	(*BalanceRequest)(nil),            // 5: bankone.BalanceRequest
	(*BalanceResponse)(nil),           // 6: bankone.BalanceResponse
	(*TransactionsRequest)(nil),       // 7: bankone.TransactionsRequest
	(*TransactionsResponse)(nil),      // 8: bankone.TransactionsResponse
	(*TransactionInfo)(nil),           // 9: bankone.TransactionInfo
	(*AccountEnquiryRequest)(nil),     // 10: bankone.AccountEnquiryRequest
	(*PNDRequest)(nil),                // 11: bankone.PNDRequest
	(*LienRequest)(nil),               // 12: bankone.LienRequest
	(*BVNRequest)(nil),                // 13: bankone.BVNRequest
	(*BankOneResponse)(nil),           // 14: bankone.BankOneResponse
}
var file_bankone_proto_depIdxs = []int32{
	9,  // 0: bankone.TransactionsResponse.transactions:type_name -> bankone.TransactionInfo
	3,  // 1: bankone.BankOneService.CreateAccountQuick:input_type -> bankone.CreateAccountQuickRequest
	4,  // 2: bankone.BankOneService.CreateCustomerAndAccount:input_type -> bankone.CreateCustomerRequest
	5,  // 3: bankone.BankOneService.GetBalance:input_type -> bankone.BalanceRequest
	7,  // 4: bankone.BankOneService.GetTransactions:input_type -> bankone.TransactionsRequest
	10, // 5: bankone.BankOneService.AccountEnquiry:input_type -> bankone.AccountEnquiryRequest
	11, // 6: bankone.BankOneService.SetPND:input_type -> bankone.PNDRequest
	12, // 7: bankone.BankOneService.SetLien:input_type -> bankone.LienRequest
	13, // 8: bankone.BankOneService.GetBVNDetails:input_type -> bankone.BVNRequest
	1,  // 9: bankone.BankOneService.InterbankTransfer:input_type -> bankone.InterbankTransferRequest
	2,  // 10: bankone.BankOneService.TransactionStatusQuery:input_type -> bankone.TSQRequest
	0,  // 11: bankone.BankOneService.GetOtherBankList:input_type -> bankone.Empty
	14, // 12: bankone.BankOneService.CreateAccountQuick:output_type -> bankone.BankOneResponse
	14, // 13: bankone.BankOneService.CreateCustomerAndAccount:output_type -> bankone.BankOneResponse
	6,  // 14: bankone.BankOneService.GetBalance:output_type -> bankone.BalanceResponse
	8,  // 15: bankone.BankOneService.GetTransactions:output_type -> bankone.TransactionsResponse
	14, // 16: bankone.BankOneService.AccountEnquiry:output_type -> bankone.BankOneResponse
	14, // 17: bankone.BankOneService.SetPND:output_type -> bankone.BankOneResponse
	14, // 18: bankone.BankOneService.SetLien:output_type -> bankone.BankOneResponse
	14, // 19: bankone.BankOneService.GetBVNDetails:output_type -> bankone.BankOneResponse
	14, // 20: bankone.BankOneService.InterbankTransfer:output_type -> bankone.BankOneResponse
	14, // 21: bankone.BankOneService.TransactionStatusQuery:output_type -> bankone.BankOneResponse
	14, // 22: bankone.BankOneService.GetOtherBankList:output_type -> bankone.BankOneResponse
	12, // [12:23] is the sub-list for method output_type
	1,  // [1:12] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_bankone_proto_init() }
func file_bankone_proto_init() {
	if File_bankone_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bankone_proto_rawDesc), len(file_bankone_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bankone_proto_goTypes,
		DependencyIndexes: file_bankone_proto_depIdxs,
		MessageInfos:      file_bankone_proto_msgTypes,
	}.Build()
	File_bankone_proto = out.File
	file_bankone_proto_goTypes = nil
	file_bankone_proto_depIdxs = nil
}
